package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra/doc"
	"github.com/trianalab/pacto/internal/app"
	"github.com/trianalab/pacto/internal/cli"
	"github.com/trianalab/pacto/internal/oci"
	"github.com/trianalab/pacto/pkg/plugin"
)

const frontMatter = `---
title: CLI Reference
layout: default
nav_order: 7
---

# CLI Reference
{: .no_toc }

All commands support ` + "`--output-format json`" + ` for programmatic consumption, ` + "`--output-format markdown`" + ` for rich markdown output (e.g. CI comments), ` + "`-v`" + ` / ` + "`--verbose`" + ` for debug-level logging, and ` + "`--help`" + ` for detailed usage.

<!-- This file is auto-generated by cmd/gendocs. Do not edit manually. -->

---

<details open markdown="block">
  <summary>Table of contents</summary>
- TOC
{:toc}
</details>

---

`

const ociVersionResolution = `## OCI version resolution

All commands that accept ` + "`oci://`" + ` references support automatic version resolution. When a reference omits the tag (e.g. ` + "`oci://ghcr.io/acme/svc-pacto`" + ` instead of ` + "`oci://ghcr.io/acme/svc-pacto:1.0.0`" + `), pacto queries the registry for available tags and selects the **highest semver version**.

For dependency references declared with a ` + "`compatibility`" + ` constraint, only tags satisfying the constraint are considered. For example, a dependency with ` + "`compatibility: \"^2.0.0\"`" + ` and available tags ` + "`1.0.0`" + `, ` + "`2.0.0`" + `, ` + "`2.3.0`" + `, ` + "`3.0.0`" + ` resolves to ` + "`2.3.0`" + `.

Non-semver tags (e.g. ` + "`latest`" + `, ` + "`main`" + `) are ignored during resolution. Digest-pinned references (` + "`@sha256:...`" + `) and explicitly tagged references are used as-is.

---

`

const footer = `---

## Environment variables

| Variable | Description |
|----------|-------------|
| ` + "`PACTO_NO_CACHE`" + ` | Set to ` + "`1`" + ` to disable OCI bundle caching (equivalent to ` + "`--no-cache`" + `) |
| ` + "`PACTO_NO_UPDATE_CHECK`" + ` | Set to ` + "`1`" + ` to disable automatic update checks |
| ` + "`PACTO_REGISTRY_USERNAME`" + ` | Registry username for authentication |
| ` + "`PACTO_REGISTRY_PASSWORD`" + ` | Registry password for authentication |
| ` + "`PACTO_REGISTRY_TOKEN`" + ` | Registry token for authentication |

---

## Authentication

Pacto follows this credential resolution chain:

1. Explicit CLI flags (` + "`--username`" + `, ` + "`--password`" + `)
2. Environment variables (` + "`PACTO_REGISTRY_USERNAME`" + `, ` + "`PACTO_REGISTRY_PASSWORD`" + `, ` + "`PACTO_REGISTRY_TOKEN`" + `)
3. Pacto config (` + "`~/.config/pacto/config.json`" + `, written by ` + "`pacto login`" + `)
4. GitHub CLI (` + "`gh auth token`" + `, for ` + "`ghcr.io`" + ` and ` + "`docker.pkg.github.com`" + ` only)
5. Docker config (` + "`~/.docker/config.json`" + `) and credential helpers
6. Cloud auto-detection (ECR, GCR, ACR)
7. Anonymous fallback

For GitHub registries, step 4 means you can skip ` + "`pacto login`" + ` entirely if you have ` + "`gh`" + ` authenticated with the ` + "`write:packages`" + ` scope (see [` + "`pacto login`" + `](#pacto-login) above).

No credentials are ever stored in contract files.
`

// commandNotes contains additional documentation appended after the
// auto-generated content for each command. These notes capture behavioural
// details, output examples, and cross-references that cannot be derived
// from the cobra command definition alone.
var commandNotes = map[string]string{
	"init": `Scaffolds a bundle with a valid ` + "`pacto.yaml`" + `, a placeholder OpenAPI spec, and a configuration JSON Schema. Only ` + "`pacto.yaml`" + ` is required — the ` + "`interfaces/`" + ` and ` + "`configuration/`" + ` directories are optional conveniences.`,

	"validate": `**Exit code:** Non-zero if validation fails.`,

	"pack": `The contract is validated before packing. If validation fails, no archive is created.`,

	"push": "If the artifact already exists in the registry, `pacto push` prints a warning and exits successfully without pushing. Use `--force` to overwrite.",

	"diff": `**Exit code:** Non-zero if breaking changes are detected.

The diff engine performs deep comparison of referenced OpenAPI specs, detecting changes at the path, method, parameter, request body, and response level. The optional ` + "`docs/`" + ` directory is ignored entirely — documentation changes never produce diff entries or affect compatibility classification.

When both bundles include an ` + "`sbom/`" + ` directory with recognized SBOM files (` + "`.spdx.json`" + ` or ` + "`.cdx.json`" + `), ` + "`pacto diff`" + ` reports package-level changes — added, removed, or modified packages (version and license). SBOM changes are informational and do not affect the overall classification or exit code.

When dependencies change between the old and new contracts (version upgrades, additions, or removals), a dependency graph diff section is displayed showing the tree of affected nodes.

See [Change Classification]({{ site.baseurl }}{% link contract-reference.md %}#change-classification-rules) for the full rules.`,

	"graph": `Dependencies resolved from local paths are annotated with ` + "`[local]`" + `. Shared dependencies (referenced by multiple parents) are annotated with ` + "`(shared)`" + `.

Reports cycles, version conflicts, and unreachable dependencies.

Sibling dependencies are resolved in parallel. OCI bundles are cached locally in ` + "`~/.cache/pacto/oci/`" + ` for faster subsequent operations. Use ` + "`--no-cache`" + ` to bypass the cache.`,

	"doc": "`--serve`, `--ui`, and `--output` are mutually exclusive.\n\nUse `--interface` to select a specific OpenAPI interface when multiple are present. Without it, an index page is shown.\n\nThe `--target` flag supports per-interface mapping: `--target api=http://localhost:3000 --target admin=http://localhost:4000`.\n\nSibling dependencies are resolved in parallel. OCI bundles are cached locally in `~/.cache/pacto/oci/` for faster subsequent operations. Use `--no-cache` to bypass the cache.",

	"login": "Credentials are stored in `~/.config/pacto/config.json` (or `$XDG_CONFIG_HOME/pacto/config.json`), keeping them separate from Docker's configuration.\n\n" +
		"### GitHub Container Registry (ghcr.io)\n\n" +
		"For GitHub registries (`ghcr.io` and `docker.pkg.github.com`), pacto can automatically reuse credentials from the [GitHub CLI](https://cli.github.com/) — no `pacto login` required.\n\n" +
		"If you already have `gh` installed and authenticated, pacto will use `gh auth token` to obtain a token transparently. To verify your setup:\n\n" +
		"```bash\n# Check if gh is authenticated\ngh auth status\n\n# Verify the token is available\ngh auth token\n```\n\n" +
		"To push container images or packages, your token needs the `write:packages` scope. If you authenticated `gh` without it, refresh your scopes:\n\n" +
		"```bash\ngh auth refresh --scopes write:packages\n```\n\n" +
		"After this, `pacto push oci://ghcr.io/...` will work without any additional login step.\n\n" +
		"If `gh` is not installed or not authenticated, pacto silently falls back to the next credential source in the chain.",

	"update": "{: .note }\n`pacto update` is not available on dev builds. If you built from source without version injection, install a release build first.\n\n" +
		"### Update notifications\n\n" +
		"When a newer version is available, pacto displays a notification after any command:\n\n" +
		"```\nA new version of pacto is available: v1.0.0 -> v1.2.0\nRun 'pacto update' to update.\n```\n\n" +
		"The check runs asynchronously and adds no latency. Results are cached for 24 hours in `~/.config/pacto/update-check.json`.\n\n" +
		"Notifications are suppressed when:\n" +
		"- Running a dev build\n" +
		"- Using `--output-format json`\n" +
		"- The `PACTO_NO_UPDATE_CHECK=1` environment variable is set",

	"dashboard": "Sources are auto-detected at startup and combined using an aggregation layer with priority-based merging. " +
		"Services are grouped by contract name across all sources.\n\n" +
		"### Dependency resolution\n\n" +
		"When OCI repository names differ from contract service names (e.g., repo `my-service-pacto` but contract has `service.name: my-service`), " +
		"the dashboard automatically builds a ref-alias map from `imageRef` and `chartRef` fields so that dependency links, graph edges, " +
		"and cross-references resolve correctly.\n\n" +
		"### Graph visualization\n\n" +
		"The built-in D3 force-directed graph supports:\n" +
		"- Drag to reposition nodes (double-click to unpin)\n" +
		"- Zoom and pan\n" +
		"- Impact chain highlighting on hover (broken nodes highlight dependents)\n" +
		"- Dynamic arrow positioning (arrows connect to the closest box edge)\n" +
		"- Source and status filtering via the legend\n\n" +
		"### Version selection\n\n" +
		"The dashboard selects the **current version** of each OCI-backed service as the highest valid semver tag. " +
		"Non-semver tags (e.g. `latest`, `main`) are excluded from version lists and never selected as the current version.\n\n" +
		"When you use \"Fetch all versions\" in the version history tab, all available versions are pulled from the OCI registry " +
		"and persisted to the local disk cache (`~/.cache/pacto/oci/`). These cached versions survive dashboard restarts " +
		"and are treated as first-class cached artifacts.\n\n" +
		"When a remote dependency is lazily resolved (via navigation to an unresolved dependency), the resolved bundle is also " +
		"cached on disk and promoted to a normal cached external artifact. Its version history can be browsed and other versions can be loaded.\n\n" +
		"### Diagnostics mode\n\n" +
		"Pass `--diagnostics` to enable debug endpoints (`/api/debug/sources` and `/api/debug/services`) " +
		"that expose raw per-source data for troubleshooting.",

	"mcp": "The server exposes the following tools:\n\n" +
		"| Tool | Description |\n" +
		"|------|-------------|\n" +
		"| `pacto_validate` | Validate a contract and return errors/warnings |\n" +
		"| `pacto_inspect` | Return the full structured contract representation |\n" +
		"| `pacto_resolve_dependencies` | Resolve the dependency graph, detecting cycles and conflicts |\n" +
		"| `pacto_list_interfaces` | List interfaces exposed by a service |\n" +
		"| `pacto_generate_docs` | Generate Markdown documentation from a contract |\n" +
		"| `pacto_explain` | Return a human-readable summary of a contract |\n" +
		"| `pacto_generate_contract` | Generate a new contract YAML from structured inputs |\n" +
		"| `pacto_suggest_dependencies` | Suggest likely dependencies based on service characteristics |\n" +
		"| `pacto_schema` | Return the Pacto JSON Schema and documentation link |\n\n" +
		"All tools accept both local directory paths and `oci://` references.\n\n" +
		"See [MCP Integration]({{ site.baseurl }}{% link mcp-integration.md %}) for detailed setup instructions with Claude and other AI tools.",
}

func main() {
	outputPath := filepath.Join("docs", "cli-reference.md")
	if len(os.Args) > 1 {
		outputPath = os.Args[1]
	}

	keychain := oci.NewKeychain(oci.CredentialOptions{})
	store := oci.NewCachedStore(oci.NewClient(keychain))
	svc := app.NewService(store, &plugin.SubprocessRunner{})
	root := cli.NewRootCommand(svc, cli.VersionInfo{Version: "dev"})

	root.DisableAutoGenTag = true
	for _, cmd := range root.Commands() {
		cmd.DisableAutoGenTag = true
	}

	var buf bytes.Buffer
	buf.WriteString(frontMatter)

	// Generate the root command docs for global flags.
	var rootBuf bytes.Buffer
	if err := doc.GenMarkdownCustom(root, &rootBuf, noLink); err != nil {
		fmt.Fprintf(os.Stderr, "error generating root docs: %v\n", err)
		os.Exit(1)
	}
	sections := parseSections(rootBuf.String())
	buf.WriteString("## Global flags\n\n")
	if opts, ok := sections["Options"]; ok {
		buf.WriteString(opts)
		buf.WriteString("\n")
	}
	buf.WriteString("\n---\n\n")

	// OCI version resolution (static section).
	buf.WriteString(ociVersionResolution)

	// Generate docs for each subcommand.
	for _, cmd := range root.Commands() {
		if !cmd.IsAvailableCommand() || cmd.IsAdditionalHelpTopicCommand() {
			continue
		}

		var cmdBuf bytes.Buffer
		if err := doc.GenMarkdownCustom(cmd, &cmdBuf, noLink); err != nil {
			fmt.Fprintf(os.Stderr, "error generating docs for %s: %v\n", cmd.Name(), err)
			os.Exit(1)
		}

		buf.WriteString(formatCommand(cmd.Name(), cmdBuf.String()))
	}

	// Remove the trailing "---\n\n" from the last command since footer starts with one.
	output := buf.String()
	output = strings.TrimSuffix(output, "---\n\n")
	buf.Reset()
	buf.WriteString(output)
	buf.WriteString(footer)

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputPath)
}

func noLink(s string) string { return "" }

// parseSections splits cobra-generated markdown into named sections.
// Section names are the H3 headings (e.g. "Synopsis", "Examples", "Options").
func parseSections(md string) map[string]string {
	sections := make(map[string]string)
	lines := strings.Split(md, "\n")

	var currentSection string
	var content strings.Builder

	for _, line := range lines {
		if heading, ok := strings.CutPrefix(line, "### "); ok {
			if currentSection != "" {
				sections[currentSection] = strings.TrimSpace(content.String())
			}
			currentSection = strings.TrimSpace(heading)
			content.Reset()
			continue
		}
		// Skip the top-level ## heading line.
		if strings.HasPrefix(line, "## ") {
			continue
		}
		if currentSection != "" {
			content.WriteString(line)
			content.WriteString("\n")
		}
	}
	if currentSection != "" {
		sections[currentSection] = strings.TrimSpace(content.String())
	}

	return sections
}

// formatCommand converts cobra-generated markdown for a subcommand into the
// desired format for the CLI reference page.
func formatCommand(name, md string) string {
	sections := parseSections(md)
	var sb strings.Builder

	fmt.Fprintf(&sb, "## `pacto %s`\n\n", name)

	// Write the description from Synopsis section.
	if synopsis, ok := sections["Synopsis"]; ok {
		// Synopsis contains: description lines, then a code block with usage.
		parts := strings.SplitN(synopsis, "```", 3)
		if len(parts) >= 1 {
			desc := strings.TrimSpace(parts[0])
			if desc != "" {
				sb.WriteString(desc)
				sb.WriteString("\n\n")
			}
		}
		// Write the usage code block.
		if len(parts) >= 3 {
			usage := strings.TrimSpace(parts[1])
			sb.WriteString("```\n")
			sb.WriteString(usage)
			sb.WriteString("\n```\n")
		}
	}

	// Write examples.
	if examples, ok := sections["Examples"]; ok {
		sb.WriteString("\n**Examples:**\n\n")
		sb.WriteString(examples)
		sb.WriteString("\n")
	}

	// Write command-specific flags (not inherited global flags).
	if opts, ok := sections["Options"]; ok {
		sb.WriteString("\n**Flags:**\n\n")
		sb.WriteString(opts)
		sb.WriteString("\n")
	}

	// Append additional notes for this command.
	if note, ok := commandNotes[name]; ok {
		sb.WriteString("\n")
		sb.WriteString(note)
		sb.WriteString("\n")
	}

	sb.WriteString("\n---\n\n")
	return sb.String()
}
