package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra/doc"
	"github.com/trianalab/pacto/v3/internal/app"
	"github.com/trianalab/pacto/v3/internal/cli"
	"github.com/trianalab/pacto/v3/pkg/oci"
	"github.com/trianalab/pacto/v3/pkg/plugin"
)

const frontMatter = `# CLI Reference

Most commands support ` + "`--output-format json`" + ` for programmatic consumption and ` + "`--output-format markdown`" + ` for rich markdown output (e.g. CI comments); the interactive and side-effecting commands (` + "`login`" + `, ` + "`logout`" + `, ` + "`update`" + `, ` + "`mcp`" + `, ` + "`dashboard`" + `) always emit text. Every command accepts ` + "`-v`" + ` / ` + "`--verbose`" + ` for debug-level logging and ` + "`--help`" + ` for detailed usage.

<!-- This file is auto-generated by cmd/gendocs. Do not edit manually. -->

---

`

const ociVersionResolution = `## OCI version resolution

All commands that accept ` + "`oci://`" + ` references support automatic version resolution. When a reference omits the tag (e.g. ` + "`oci://ghcr.io/acme/svc-pacto`" + ` instead of ` + "`oci://ghcr.io/acme/svc-pacto:1.0.0`" + `), pacto queries the registry for available tags and selects the **highest semver version**.

For dependency references declared with a ` + "`compatibility`" + ` constraint, only tags satisfying the constraint are considered. For example, a dependency with ` + "`compatibility: \"^2.0.0\"`" + ` and available tags ` + "`1.0.0`" + `, ` + "`2.0.0`" + `, ` + "`2.3.0`" + `, ` + "`3.0.0`" + ` resolves to ` + "`2.3.0`" + `.

Non-semver tags (e.g. ` + "`latest`" + `, ` + "`main`" + `) are ignored during resolution. Digest-pinned references (` + "`@sha256:...`" + `) and explicitly tagged references are used as-is.

!!! note "Constraints apply to the CLI's dependency graph, not dashboard discovery"
    ` + "`compatibility`" + ` constraints are applied by the CLI when resolving a contract's
    **declared dependencies** (e.g. ` + "`pacto graph`" + `). The **dashboard's** version
    discovery selects the highest semver tag and does **not** apply per-dependency
    ` + "`compatibility`" + ` constraints. Root-contract pulls (a tagless top-level ` + "`oci://`" + `
    ref) also select the highest semver tag with no constraint.

---

`

const footer = `---

## Environment variables

| Variable | Description |
|----------|-------------|
| ` + "`PACTO_CACHE_DIR`" + ` | Cache directory for the ` + "`pacto dashboard`" + ` bundle scan. The core CLI cache location is controlled by ` + "`XDG_CACHE_HOME`" + ` (see below). |
| ` + "`PACTO_NO_CACHE`" + ` | Set to ` + "`1`" + ` to disable OCI bundle caching (equivalent to ` + "`--no-cache`" + `) |
| ` + "`PACTO_NO_ANIM`" + ` | Set to ` + "`1`" + ` to disable spinners and animations (equivalent to ` + "`--no-anim`" + `) |
| ` + "`PACTO_NO_UPDATE_CHECK`" + ` | Set to ` + "`1`" + ` to disable automatic update checks |
| ` + "`PACTO_REGISTRY_USERNAME`" + ` | Registry username for authentication |
| ` + "`PACTO_REGISTRY_PASSWORD`" + ` | Registry password for authentication |
| ` + "`PACTO_REGISTRY_TOKEN`" + ` | Registry token for authentication |
| ` + "`XDG_CONFIG_HOME`" + ` | Override config directory (default: ` + "`~/.config`" + `). Affects ` + "`pacto login`" + ` credentials and update check cache |
| ` + "`XDG_CACHE_HOME`" + ` | Override cache directory (default: ` + "`~/.cache`" + `). Affects OCI bundle cache location |

### Dashboard environment variables

The following variables configure the dashboard when set (see also [Dashboard Container](dashboard-docker.md)):

| Variable | Description |
|----------|-------------|
| ` + "`PACTO_DASHBOARD_REPO`" + ` | Comma-separated OCI repositories (fallback when no positional args) |
| ` + "`PACTO_DASHBOARD_HOST`" + ` | Bind address (default: ` + "`127.0.0.1`" + `) |
| ` + "`PACTO_DASHBOARD_PORT`" + ` | HTTP port (default: ` + "`3000`" + `) |
| ` + "`PACTO_DASHBOARD_NAMESPACE`" + ` | Kubernetes namespace filter (empty = all) |
| ` + "`PACTO_DASHBOARD_DIAGNOSTICS`" + ` | Enable debug endpoints |

---

## Authentication

Pacto follows this credential resolution chain:

1. Environment variables (` + "`PACTO_REGISTRY_TOKEN`" + `, or ` + "`PACTO_REGISTRY_USERNAME`" + ` + ` + "`PACTO_REGISTRY_PASSWORD`" + `)
2. Pacto config (` + "`~/.config/pacto/config.json`" + `, written by ` + "`pacto login`" + ` — where ` + "`--username`" + ` / ` + "`--password`" + ` are persisted)
3. GitHub CLI (` + "`gh auth token`" + `, for ` + "`ghcr.io`" + ` and ` + "`docker.pkg.github.com`" + ` only)
4. Docker config (` + "`~/.docker/config.json`" + `) and credential helpers (including cloud-registry helpers for ECR, GCR and ACR)
5. Anonymous fallback

For GitHub registries, step 3 means you can skip ` + "`pacto login`" + ` entirely if you have ` + "`gh`" + ` authenticated with the ` + "`write:packages`" + ` scope (see [` + "`pacto login`" + `](#pacto-login) above).

No credentials are ever stored in contract files.
`

// commandNotes contains additional documentation appended after the
// auto-generated content for each command. These notes capture behavioural
// details, output examples, and cross-references that cannot be derived
// from the cobra command definition alone.
var commandNotes = map[string]string{
	"init": `Scaffolds a bundle with a valid ` + "`pacto.yaml`" + `, a placeholder OpenAPI spec, and a configuration JSON Schema. Only ` + "`pacto.yaml`" + ` is required — the ` + "`interfaces/`" + ` and ` + "`configuration/`" + ` directories are optional conveniences.`,

	"validate": "The `--readiness` gate is **opt-in** because it is time-dependent: it compares each check's `expires` against the run time, which would make plain `validate` non-deterministic. " +
		"Without the flag, validation only checks the contract's structure and rules (readiness checks are still validated for shape, but the freshness gate is not enforced). " +
		"See the [readiness reference](contract-reference/sections.md#readiness) for the score and gate semantics.\n\n" +
		"**Exit code:** Non-zero if validation fails.",

	"explain": "**Readiness output.** When the contract declares a `readiness` section (a `pactoVersion: \"2.0\"` feature), `explain` adds a Readiness block: " +
		"the derived **Score**, the **Gate** result (`PASS`/`FAIL` with `score / minScore`), **Earned** and **Total Weight**, " +
		"the partial credit multiplier, the assessment `expires` date with countdown (or an Expired state), and a per-check table " +
		"showing each check's declared `status` (`done`/`partial`/`not-done`/`deferred`), `category`, weight, earned weight, and `evidence`. " +
		"The Readiness block also includes a revision-history table when `history[]` is present. " +
		"`--output-format json` includes the same data plus `doneCount`, `partialCount`, `notDoneCount`, `deferredCount`, and `expired` (boolean). " +
		"Readiness status is time-dependent — the score is 0 when the current date is past the assessment-level `expires`.",

	"pack": "The contract is validated before packing. If validation fails, no archive is created.\n\n" +
		"Files matched by `.pactoignore` are excluded from the archive — see [Packaging ignore](pactoignore.md).",

	"generate": "`pacto generate <plugin>` invokes the `pacto-plugin-<plugin>` binary. See [Plugins](plugins.md) for plugin discovery, the plugin registry, and the official plugins bundled with Pacto.",

	"lock": "See [Lockfile](lockfile.md) for the lock model, drift enforcement, and how `.pactoignore` keeps a `pacto.lock` out of a pushed bundle.",

	"push": "If the artifact already exists in the registry, `pacto push` prints a warning and exits successfully without pushing. Use `--force` to overwrite.\n\n" +
		"!!! note \"`--values` has no `-f` shorthand on push\"\n" +
		"    On every other override-taking command `-f` is the shorthand for `--values`. On `pacto push`, `-f` is `--force`, so `--values` must be spelled out in full here.",

	"diff": `**Exit code:** Non-zero if breaking changes are detected.

The diff engine performs deep comparison of referenced OpenAPI specs, detecting changes at the path, method, parameter, request body, and response level. The optional ` + "`docs/`" + ` directory is ignored entirely — documentation changes never produce diff entries or affect compatibility classification.

When both bundles include an ` + "`sbom/`" + ` directory with recognized SBOM files (` + "`.spdx.json`" + ` or ` + "`.cdx.json`" + `), ` + "`pacto diff`" + ` reports package-level changes — added, removed, or modified packages (version and license). SBOM changes are informational and do not affect the overall classification or exit code.

When dependencies change between the old and new contracts (version upgrades, additions, or removals), a dependency graph diff section is displayed showing the tree of affected nodes.

See [Change Classification](contract-reference/diff.md#change-classification-rules) for the full rules.`,

	"graph": `Dependencies resolved from local paths are annotated with ` + "`[local]`" + `. Shared dependencies (referenced by multiple parents) are annotated with ` + "`(shared)`" + `.

Reports cycles, version conflicts, and unreachable dependencies.

Sibling dependencies are resolved in parallel. OCI bundles are cached locally in ` + "`~/.cache/pacto/oci/`" + ` for faster subsequent operations. Use ` + "`--no-cache`" + ` to bypass the cache.`,

	"doc": "Markdown prints to stdout by default. `-o DIR` writes `DIR/<service>.md`. `-o NAME.html` writes a self-contained static documentation site (a directory) that reuses the dashboard UI offline.\n\n`--serve` serves that static site locally. `--ui swagger` launches an interactive API explorer.\n\n`--serve`, `--ui` and `-o` are mutually exclusive. Use `--interface` to pick one OpenAPI interface with `--ui`. `--target` and `--target iface=url` point try-it-out at a backend.\n\nSibling dependencies are resolved in parallel. OCI bundles cache under `~/.cache/pacto/oci/`. `--no-cache` bypasses the cache.",

	"login": "Credentials are stored in `~/.config/pacto/config.json` (or `$XDG_CONFIG_HOME/pacto/config.json`), keeping them separate from Docker's configuration.\n\n" +
		"### GitHub Container Registry (ghcr.io)\n\n" +
		"For GitHub registries (`ghcr.io` and `docker.pkg.github.com`), pacto can automatically reuse credentials from the [GitHub CLI](https://cli.github.com/) — no `pacto login` required.\n\n" +
		"If you already have `gh` installed and authenticated, pacto will use `gh auth token` to obtain a token transparently. To verify your setup:\n\n" +
		"```bash\n# Check if gh is authenticated\ngh auth status\n\n# Verify the token is available\ngh auth token\n```\n\n" +
		"To push container images or packages, your token needs the `write:packages` scope. If you authenticated `gh` without it, refresh your scopes:\n\n" +
		"```bash\ngh auth refresh --scopes write:packages\n```\n\n" +
		"After this, `pacto push oci://ghcr.io/...` will work without any additional login step.\n\n" +
		"If `gh` is not installed or not authenticated, pacto silently falls back to the next credential source in the chain.",

	"update": "!!! note\n    `pacto update` is not available on dev builds. If you built from source without version injection, install a release build first.\n\n" +
		"### Update notifications\n\n" +
		"When a newer version is available, pacto displays a notification after any command:\n\n" +
		"```\nA new version of pacto is available: v1.0.0 -> v1.2.0\nRun 'pacto update' to update.\n```\n\n" +
		"The check runs asynchronously and adds no latency. Results are cached for 24 hours in `~/.config/pacto/update-check.json`.\n\n" +
		"Notifications are suppressed when:\n" +
		"- Running a dev build\n" +
		"- Using `--output-format json` or `--output-format markdown` (the notice shows only for text output)\n" +
		"- The `PACTO_NO_UPDATE_CHECK=1` environment variable is set",

	"dashboard": "It auto-detects sources: pass OCI repositories as arguments, or run it next to the operator (with a kubeconfig) and it discovers OCI repositories from each Pacto resource's `status.contract.resolvedRef`. Use `--no-cache` for a cold start (it skips scanning pre-existing cached bundles; bundles fetched during the session are still cached), and `--diagnostics` to expose the `/api/debug/*` endpoints.\n\n" +
		"For the source model, contract-first merge priority (`local` > `oci` > `cache`) and version-tracking design, see [Architecture](architecture.md). For a tour of what the dashboard surfaces, see [For platform engineers](platform-engineers.md); to run it as a container, see [Dashboard container](dashboard-docker.md).",

	"mcp": "The server exposes the following tools:\n\n" +
		"| Tool | Description |\n" +
		"|------|-------------|\n" +
		"| `pacto_create` | Create a new contract from intent-level inputs (name, description, interfaces, runtime semantics). Supports dry run. |\n" +
		"| `pacto_edit` | Edit an existing contract — add/remove interfaces and dependencies, change runtime, update metadata. Supports dry run. |\n" +
		"| `pacto_check` | Validate a contract and return errors, warnings, and actionable improvement suggestions. |\n" +
		"| `pacto_schema` | Return the Pacto format explanation and full JSON Schema reference. |\n\n" +
		"These four authoring tools operate on local contract directories (they read and write `pacto.yaml` on disk) and do not resolve `oci://` refs.\n\n" +
		"### Server modes\n\n" +
		"The default server exposes the authoring tools above. Three flags select a different server instead, and they cannot be combined — passing more than one is an error, never a silent choice:\n\n" +
		"| Invocation | Server |\n" +
		"|------------|--------|\n" +
		"| `pacto mcp` | Authoring tools. |\n" +
		"| `pacto mcp <bundle-ref>` | Authoring tools plus the bundle's OpenAPI operations as executable agent tools, alongside a `pacto_skill` tool for any bundled skills. |\n" +
		"| `pacto mcp --fleet` | Read-only [operational-graph](operational-graph.md) query tools. |\n" +
		"| `pacto mcp --root <ref> [--root <ref>]` | A read-only contract catalog discovered from the named roots. |\n\n" +
		"`--root` is repeatable and takes a local bundle directory or an `oci://` reference. The roots and their dependency closure are resolved once, at startup, through the same reference parsing, credentials and cache the rest of the CLI uses; after that the session is frozen, so a tag that moves in a registry does not change any answer. Roots that do not resolve stay visible with a classified reason and the catalog reports itself as partial. Nothing is crawled, nothing is refreshed and nothing is persisted.\n\n" +
		"See [MCP Integration](mcp-integration.md) for detailed setup with Claude and other AI tools, [Agent capabilities](mcp-integration.md#agent-capabilities) for serving a bundle's operations as tools, and [Contract catalog discovery](mcp-integration.md#contract-catalog-discovery) for the catalog surface.",
}

func main() {
	outputPath := filepath.Join("docs", "cli-reference.md")
	if len(os.Args) > 1 {
		outputPath = os.Args[1]
	}

	keychain := oci.NewKeychain(oci.CredentialOptions{})
	store := oci.NewCachedStore(oci.NewClient(keychain))
	svc := app.NewService(store, &plugin.SubprocessRunner{})
	root := cli.NewRootCommand(svc, cli.VersionInfo{Version: "dev"})

	root.DisableAutoGenTag = true
	for _, cmd := range root.Commands() {
		cmd.DisableAutoGenTag = true
	}

	var buf bytes.Buffer
	buf.WriteString(frontMatter)

	// Generate the root command docs for global flags.
	var rootBuf bytes.Buffer
	if err := doc.GenMarkdownCustom(root, &rootBuf, noLink); err != nil {
		fmt.Fprintf(os.Stderr, "error generating root docs: %v\n", err)
		os.Exit(1)
	}
	sections := parseSections(rootBuf.String())
	buf.WriteString("## Global flags\n\n")
	if opts, ok := sections["Options"]; ok {
		buf.WriteString(opts)
		buf.WriteString("\n")
	}
	buf.WriteString("\n---\n\n")

	// OCI version resolution (static section).
	buf.WriteString(ociVersionResolution)

	// Generate docs for each subcommand.
	for _, cmd := range root.Commands() {
		if !cmd.IsAvailableCommand() || cmd.IsAdditionalHelpTopicCommand() {
			continue
		}

		var cmdBuf bytes.Buffer
		if err := doc.GenMarkdownCustom(cmd, &cmdBuf, noLink); err != nil {
			fmt.Fprintf(os.Stderr, "error generating docs for %s: %v\n", cmd.Name(), err)
			os.Exit(1)
		}

		buf.WriteString(formatCommand(cmd.Name(), cmdBuf.String()))
	}

	// Remove the trailing "---\n\n" from the last command since footer starts with one.
	output := buf.String()
	output = strings.TrimSuffix(output, "---\n\n")
	buf.Reset()
	buf.WriteString(output)
	buf.WriteString(footer)

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputPath)
}

func noLink(s string) string { return "" }

// parseSections splits cobra-generated markdown into named sections.
// Section names are the H3 headings (e.g. "Synopsis", "Examples", "Options").
func parseSections(md string) map[string]string {
	sections := make(map[string]string)
	lines := strings.Split(md, "\n")

	var currentSection string
	var content strings.Builder

	for _, line := range lines {
		if heading, ok := strings.CutPrefix(line, "### "); ok {
			if currentSection != "" {
				sections[currentSection] = strings.TrimSpace(content.String())
			}
			currentSection = strings.TrimSpace(heading)
			content.Reset()
			continue
		}
		// Skip the top-level ## heading line.
		if strings.HasPrefix(line, "## ") {
			continue
		}
		if currentSection != "" {
			content.WriteString(line)
			content.WriteString("\n")
		}
	}
	if currentSection != "" {
		sections[currentSection] = strings.TrimSpace(content.String())
	}

	return sections
}

// formatCommand converts cobra-generated markdown for a subcommand into the
// desired format for the CLI reference page.
func formatCommand(name, md string) string {
	sections := parseSections(md)
	var sb strings.Builder

	fmt.Fprintf(&sb, "## `pacto %s`\n\n", name)

	// Write the description from Synopsis section.
	if synopsis, ok := sections["Synopsis"]; ok {
		// Synopsis contains: description lines, then a code block with usage.
		parts := strings.SplitN(synopsis, "```", 3)
		if len(parts) >= 1 {
			desc := strings.TrimSpace(parts[0])
			if desc != "" {
				sb.WriteString(desc)
				sb.WriteString("\n\n")
			}
		}
		// Write the usage code block.
		if len(parts) >= 3 {
			usage := strings.TrimSpace(parts[1])
			sb.WriteString("```\n")
			sb.WriteString(usage)
			sb.WriteString("\n```\n")
		}
	}

	// Write examples.
	if examples, ok := sections["Examples"]; ok {
		sb.WriteString("\n**Examples:**\n\n")
		sb.WriteString(examples)
		sb.WriteString("\n")
	}

	// Write command-specific flags (not inherited global flags).
	if opts, ok := sections["Options"]; ok {
		sb.WriteString("\n**Flags:**\n\n")
		sb.WriteString(opts)
		sb.WriteString("\n")
	}

	// Append additional notes for this command.
	if note, ok := commandNotes[name]; ok {
		sb.WriteString("\n")
		sb.WriteString(note)
		sb.WriteString("\n")
	}

	sb.WriteString("\n---\n\n")
	return sb.String()
}
