package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"github.com/trianalab/pacto/v3/internal/app"
	"github.com/trianalab/pacto/v3/internal/cli"
	"github.com/trianalab/pacto/v3/pkg/oci"
	"github.com/trianalab/pacto/v3/pkg/plugin"
)

const frontMatter = `# CLI Reference

Every command accepts ` + "`-v`" + ` / ` + "`--verbose`" + ` for debug-level logging and ` + "`--help`" + ` for detailed usage. ` + "`--output-format`" + ` is a global flag taking ` + "`text`" + ` (the default), ` + "`json`" + ` or ` + "`markdown`" + `.

!!! warning "What ` + "`--output-format`" + ` does and does not promise"
    Read this before you parse Pacto's output in a script.

    - **` + "`json`" + ` describes a *successful* result.** When a command cannot produce
      its result at all — an unreachable reference, a missing ` + "`pacto.lock`" + ` — the
      error goes to **stderr as plain text and stdout stays empty**, whatever
      ` + "`--output-format`" + ` said. But a *verdict* of "no" is a result, not a
      failure: ` + "`pacto validate`" + ` on an invalid contract and ` + "`pacto diff`" + ` on a
      breaking change both print their whole JSON document to stdout **and**
      exit 1. So the exit code does not tell you whether there is anything to parse —
      an empty stdout does. Read stdout when it is non-empty; read the exit code
      for the verdict.
    - **` + "`markdown`" + ` is implemented by ` + "`pacto diff`" + ` only**, for posting a diff as a
      CI comment. Every other command silently renders text instead.
    - **Key casing is not uniform.** ` + "`pacto validate`" + ` emits capitalised keys
      (` + "`\"Path\"`" + `, ` + "`\"Valid\"`" + `, ` + "`\"Errors\"`" + `); every other command emits camelCase
      (` + "`\"path\"`" + `, ` + "`\"root\"`" + `, ` + "`\"upToDate\"`" + `). Match the command you are calling.
    - **An unrecognised value is ignored, not rejected.** ` + "`--output-format yaml`" + `
      prints text and no warning — there is no YAML output — so a typo is
      indistinguishable from success.

    The interactive and side-effecting commands (` + "`login`" + `, ` + "`logout`" + `, ` + "`update`" + `,
    ` + "`mcp`" + `, ` + "`dashboard`" + `) inherit the flag from the root command and always emit text.

<!-- This file is auto-generated by cmd/gendocs. Do not edit manually. -->

---

`

const exitCodes = `## Exit codes

Pacto exits ` + "`0`" + ` or ` + "`1`" + ` and nothing else. ` + "`0`" + ` means the command produced its
result and the result was acceptable; ` + "`1`" + ` means anything else. Because there is
no third code, **the exit status alone never distinguishes "the check failed"
from "the command could not run"**.

| Exits ` + "`1`" + ` | Exits ` + "`0`" + ` |
| --- | --- |
| ` + "`pacto diff`" + ` where the overall classification is ` + "`BREAKING`" + ` | a ` + "`POTENTIAL_BREAKING`" + ` or ` + "`NON_BREAKING`" + ` diff |
| ` + "`pacto validate`" + ` reporting at least one error | validation that reported only warnings |
| ` + "`pacto lock --check`" + ` on a stale lockfile, or with none at all (` + "`LOCK_MISSING`" + `) | a lockfile that is up to date |
| **any command that could not run** — an unresolvable reference, an unreadable bundle, an unknown flag | ` + "`pacto impact`" + ` run on declared-only sources, *whatever* it classifies (see below) |

Two rows deserve emphasis, because both silently break a CI gate:

- A ` + "`pacto diff`" + ` against a reference that does not exist exits ` + "`1`" + ` exactly like a
  breaking change does.
- ` + "`pacto impact`" + ` exits non-zero only when the change is breaking **and** a live
  source shows an incompatible consumer. With declared-only sources there are no
  consumers to find, so it prints ` + "`Classification: BREAKING`" + ` and still exits ` + "`0`" + `.

**Use stdout, not the exit code, to tell a verdict from a failure.** A command
that produced a verdict writes it to stdout and puts a one-line summary on
stderr. A command that could not run writes *nothing* to stdout:

| Invocation | Exit | stdout | stderr |
| --- | --- | --- | --- |
| ` + "`pacto diff --output-format json OLD NEW`" + ` (breaking) | ` + "`1`" + ` | the full JSON result | ` + "`breaking changes detected`" + ` |
| ` + "`pacto diff --output-format json oci://…/absent:1.0.0 NEW`" + ` | ` + "`1`" + ` | *empty* | ` + "`old contract: artifact not found: …`" + ` |

So the rule for a script is: branch on stdout when it is non-empty, and treat an
empty stdout with a non-zero exit as a tool failure rather than a verdict.

!!! warning "JSON key casing is not uniform"
    ` + "`pacto validate`" + ` emits ` + "`Path`" + `, ` + "`Valid`" + ` and ` + "`Errors`" + ` in PascalCase; every other
    command emits camelCase (` + "`oldPath`" + `, ` + "`classification`" + `). One parser will not read
    both without allowing for it.

---

`

const ociVersionResolution = `## OCI version resolution

All commands that accept ` + "`oci://`" + ` references support automatic version resolution. When a reference omits the tag (e.g. ` + "`oci://ghcr.io/acme/svc-pacto`" + ` instead of ` + "`oci://ghcr.io/acme/svc-pacto:1.0.0`" + `), pacto queries the registry for available tags and selects the **highest semver version**.

For dependency references declared with a ` + "`compatibility`" + ` constraint, only tags satisfying the constraint are considered. For example, a dependency with ` + "`compatibility: \"^2.0.0\"`" + ` and available tags ` + "`1.0.0`" + `, ` + "`2.0.0`" + `, ` + "`2.3.0`" + `, ` + "`3.0.0`" + ` resolves to ` + "`2.3.0`" + `.

Non-semver tags (e.g. ` + "`latest`" + `, ` + "`main`" + `) are ignored during resolution. Digest-pinned references (` + "`@sha256:...`" + `) and explicitly tagged references are used as-is.

!!! note "Constraints apply to the CLI's dependency graph, not dashboard discovery"
    ` + "`compatibility`" + ` constraints are applied by the CLI when resolving a contract's
    **declared dependencies** (e.g. ` + "`pacto graph`" + `). The **dashboard's** version
    discovery selects the highest semver tag and does **not** apply per-dependency
    ` + "`compatibility`" + ` constraints. Root-contract pulls (a tagless top-level ` + "`oci://`" + `
    ref) also select the highest semver tag with no constraint.

---

`

const footer = `---

## Environment variables

Boolean variables are parsed the way Go parses a boolean: ` + "`1`" + `, ` + "`t`" + `, ` + "`T`" + `,
` + "`true`" + `, ` + "`TRUE`" + ` and ` + "`True`" + ` enable them. Anything else — including ` + "`yes`" + ` and
` + "`on`" + ` — reads as *off*, silently. The two exceptions are called out in the table.

| Variable | Description |
|----------|-------------|
| ` + "`PACTO_CACHE_DIR`" + ` | Cache directory for the ` + "`pacto dashboard`" + ` bundle scan. The core CLI cache location is controlled by ` + "`XDG_CACHE_HOME`" + ` (see below). |
| ` + "`PACTO_NO_CACHE`" + ` | Boolean. Disable OCI bundle caching (equivalent to ` + "`--no-cache`" + `) |
| ` + "`PACTO_NO_ANIM`" + ` | **Any non-empty value** disables spinners and animations (equivalent to ` + "`--no-anim`" + `). ` + "`PACTO_NO_ANIM=0`" + ` also disables them. |
| ` + "`PACTO_NO_UPDATE_CHECK`" + ` | **Exactly ` + "`1`" + `** disables automatic update checks. No other value has any effect. |
| ` + "`PACTO_REGISTRY_USERNAME`" + ` | Registry username for authentication |
| ` + "`PACTO_REGISTRY_PASSWORD`" + ` | Registry password for authentication |
| ` + "`PACTO_REGISTRY_TOKEN`" + ` | Registry token for authentication |
| ` + "`PACTO_INSECURE_REGISTRIES`" + ` | Comma-separated registry **hosts** the Evidence Server may reach over plain HTTP instead of HTTPS. Scoped per host, so HTTPS registries are unaffected, and scoped to the evidence commands — ` + "`pacto push`" + ` and ` + "`pacto pull`" + ` do not read it. Loopback hosts are already plain HTTP without being listed. Intended for a controlled in-cluster registry, never the public internet: it disables transport encryption, so credentials and payloads travel in the clear. |
| ` + "`PACTO_EVIDENCE_SOURCE_URL`" + ` | Base URL of an Evidence Server whose read-only [operational-graph](operational-graph.md) contribution ` + "`pacto dashboard`" + ` should consume. Set by the operator when it wires a managed Evidence Server; unset means *no evidence source configured*, which is not the same as an unavailable one. |
| ` + "`XDG_CONFIG_HOME`" + ` | Override config directory (default: ` + "`~/.config`" + `). Affects ` + "`pacto login`" + ` credentials and update check cache |
| ` + "`XDG_CACHE_HOME`" + ` | Override cache directory (default: ` + "`~/.cache`" + `). Affects OCI bundle cache location |

### Dashboard environment variables

The following variables configure the dashboard when set (see also [Dashboard Container](dashboard-docker.md)). Each mirrors the flag named beside it: an explicitly passed flag wins, and otherwise the variable overrides that flag's default.

| Variable | Flag | Description |
|----------|------|-------------|
| ` + "`PACTO_DASHBOARD_REPO`" + ` | *(positional args)* | **Comma**-separated OCI repositories, used only when no positional ` + "`oci://`" + ` argument is given |
| ` + "`PACTO_DASHBOARD_HOST`" + ` | ` + "`--host`" + ` | Bind address (default: ` + "`127.0.0.1`" + `) |
| ` + "`PACTO_DASHBOARD_PORT`" + ` | ` + "`--port`" + ` | HTTP port (default: ` + "`3000`" + `) |
| ` + "`PACTO_DASHBOARD_NAMESPACE`" + ` | ` + "`--namespace`" + ` | Kubernetes namespace filter (empty = all) |
| ` + "`PACTO_DASHBOARD_DIAGNOSTICS`" + ` | ` + "`--diagnostics`" + ` | Boolean. Expose the ` + "`/api/debug/*`" + ` endpoints and the source diagnostics panel |
| ` + "`PACTO_DASHBOARD_CORS_ORIGIN`" + ` | ` + "`--cors-origin`" + ` | One explicit origin allowed to call the API. Unset means same-origin only. |
| ` + "`PACTO_DASHBOARD_TRACES`" + ` | ` + "`--traces`" + ` | OTLP/JSON trace files to fold observed dependencies from |
| ` + "`PACTO_DASHBOARD_TRACE_SOURCES`" + ` | ` + "`--trace-source`" + ` | Named offline trace sources as ` + "`NAME=PATH`" + ` |

!!! warning "The two list variables split on **whitespace**, not commas"
    ` + "`PACTO_DASHBOARD_TRACES`" + ` and ` + "`PACTO_DASHBOARD_TRACE_SOURCES`" + ` go through the
    same generic flag binding as every other dashboard variable, which splits a
    multi-valued string on spaces. ` + "`PACTO_DASHBOARD_TRACES=\"a.json b.json\"`" + ` supplies
    two files; ` + "`PACTO_DASHBOARD_TRACES=a.json,b.json`" + ` supplies **one**, named
    ` + "`a.json,b.json`" + `. ` + "`PACTO_DASHBOARD_REPO`" + ` is the odd one out — it is read
    directly and does split on commas.

    Neither mistake stops the dashboard: a trace file it cannot read is skipped and
    the server still starts, so the symptom is missing observed dependencies rather
    than an error. Check the snapshot's reported limitations if the operational
    graph looks emptier than you expect.

---

## Authentication

Pacto follows this credential resolution chain:

1. Environment variables (` + "`PACTO_REGISTRY_TOKEN`" + `, or ` + "`PACTO_REGISTRY_USERNAME`" + ` + ` + "`PACTO_REGISTRY_PASSWORD`" + `)
2. Pacto config (` + "`~/.config/pacto/config.json`" + `, written by ` + "`pacto login`" + ` — where ` + "`--username`" + ` / ` + "`--password`" + ` are persisted)
3. GitHub CLI (` + "`gh auth token`" + `, for ` + "`ghcr.io`" + ` and ` + "`docker.pkg.github.com`" + ` only)
4. Docker config (` + "`~/.docker/config.json`" + `) and credential helpers (including cloud-registry helpers for ECR, GCR and ACR)
5. Anonymous fallback

For GitHub registries, step 3 means you can skip ` + "`pacto login`" + ` entirely if you have ` + "`gh`" + ` authenticated with the ` + "`write:packages`" + ` scope (see [` + "`pacto login`" + `](#pacto-login) above).

No credentials are ever stored in contract files.
`

// commandNotes contains additional documentation appended after the
// auto-generated content for each command. These notes capture behavioural
// details, output examples, and cross-references that cannot be derived
// from the cobra command definition alone.
var commandNotes = map[string]string{
	"init": `Scaffolds three files: a valid ` + "`pacto.yaml`" + `, a placeholder OpenAPI spec at ` + "`interfaces/openapi.yaml`" + `, and a configuration JSON Schema at ` + "`configuration/schema.json`" + `.

` + "`<name>`" + ` is the service name, not a path: it becomes the directory *and* ` + "`service.name`" + `, which must match ` + "`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`" + `. ` + "`pacto init fleet/checkout-web`" + ` therefore scaffolds a bundle that does not validate — ` + "`service.name`" + ` gets the whole path and fails ` + "`SCHEMA_VIOLATION`" + `. To scaffold inside a directory, ` + "`cd`" + ` there first and pass the bare name.

All three are required **by the scaffolded contract**, because its ` + "`interfaces:`" + ` and ` + "`configurations:`" + ` sections point at the other two files. Deleting a directory without also deleting the section that references it fails validation with ` + "`FILE_NOT_FOUND`" + `. A contract that declares neither section needs only ` + "`pacto.yaml`" + `, so drop the section and the directory together.

!!! note "The scaffold does not pass ` + "`validate --readiness`" + `, by design"
    Its two placeholder readiness claims are ` + "`not-done`" + `, which scores 0 against the
    scaffolded ` + "`minScore: 80`" + ` and fails with ` + "`READINESS_GATE_UNMET`" + `. Plain
    ` + "`pacto validate`" + ` passes, because the gate is opt-in. Fill the claims in as the
    work lands — the placeholder is the starting position of a real assessment, not a
    template to delete.`,

	"validate": "The `--readiness` gate is **opt-in** because it is time-dependent: it compares the assessment's single `readiness.expires` date against the run time, which would make plain `validate` non-deterministic. Expiry is declared once for the whole assessment — individual claims carry no `expires` field, and adding one fails to load with `PARSE_ERROR`. " +
		"Without the flag, validation only checks the contract's structure and rules (readiness checks are still validated for shape, but the freshness gate is not enforced). " +
		"See the [readiness reference](contract-reference/sections.md#readiness) for the score and gate semantics.\n\n" +
		"**Exit code:** Non-zero if validation fails.",

	"explain": "**What it covers.** The text output summarises identity, workload, state, capabilities, interfaces, dependencies and readiness. " +
		"It does **not** render `configurations` or `policies` — read those with `pacto doc`, or from `pacto.yaml` directly. " +
		"`metadata` is carried by `--output-format json` only; the text output omits it.\n\n" +
		"**Readiness output.** When the contract declares a `readiness` section (a `pactoVersion: \"2.0\"` feature), `explain` adds a Readiness block: " +
		"the derived **Score**, the **Gate** result (`PASS`/`FAIL` with `score / minScore`), **Earned** and **Total Weight**, " +
		"the partial credit multiplier, the assessment `expires` date with countdown (or an Expired state), and a per-check table " +
		"showing each check's declared `status` (`done`/`partial`/`not-done`/`deferred`), `category`, weight, earned weight, and `evidence`. " +
		"The Readiness block also includes a revision-history table when `history[]` is present. " +
		"`--output-format json` includes the same data plus `doneCount`, `partialCount`, `notDoneCount`, `deferredCount`, and `expired` (boolean). " +
		"Readiness status is time-dependent — the score is 0 when the current date is past the assessment-level `expires`.",

	"pack": "The contract is validated before packing. If validation fails, no archive is created.\n\n" +
		"Files matched by `.pactoignore` are excluded from the archive — see [Packaging ignore](pactoignore.md).",

	"generate": "`pacto generate <plugin>` invokes the `pacto-plugin-<plugin>` binary. See [Plugins](plugins.md) for plugin discovery, the plugin registry, and the official plugins bundled with Pacto.",

	"lock": "See [Lockfile](lockfile.md) for the lock model, drift enforcement, and how `.pactoignore` keeps a `pacto.lock` out of a pushed bundle.",

	"push": "If the artifact already exists in the registry, `pacto push` prints a warning and exits successfully without pushing. Use `--force` to overwrite.\n\n" +
		"!!! note \"`--values` has no `-f` shorthand on push\"\n" +
		"    On every other override-taking command `-f` is the shorthand for `--values`. On `pacto push`, `-f` is `--force`, so `--values` must be spelled out in full here.",

	"diff": `**Exit code:** ` + "`1`" + ` when the overall classification is ` + "`BREAKING`" + ` — and also ` + "`1`" + ` when the diff could not be produced at all, so a non-zero exit is not by itself a contract verdict. See [Exit codes](#exit-codes) for how to tell the two apart. A ` + "`POTENTIAL_BREAKING`" + ` result exits ` + "`0`" + `, so a CI gate that wants to stop on it has to read the classification rather than the exit code.

The diff engine performs deep comparison of referenced OpenAPI specs, detecting changes at the path, method, parameter, request body, and response level. The optional ` + "`docs/`" + ` directory is ignored entirely — documentation changes never produce diff entries or affect compatibility classification.

When both bundles include an ` + "`sbom/`" + ` directory with recognized SBOM files (` + "`.spdx.json`" + ` or ` + "`.cdx.json`" + `), ` + "`pacto diff`" + ` reports package-level changes — added, removed, or modified packages (version and license). SBOM changes are informational and do not affect the overall classification or exit code.

When dependencies change between the old and new contracts (version upgrades, additions, or removals), a dependency graph diff section is displayed showing the tree of affected nodes.

See [Change Classification](contract-reference/diff.md#change-classification-rules) for the full rules.`,

	"graph": `Dependencies resolved from local paths are annotated with ` + "`[local]`" + `. Shared dependencies (referenced by multiple parents) are annotated with ` + "`(shared)`" + `.

Reports cycles, version conflicts, and unreachable dependencies.

Sibling dependencies are resolved in parallel. OCI bundles are cached locally in ` + "`~/.cache/pacto/oci/`" + ` for faster subsequent operations. Use ` + "`--no-cache`" + ` to bypass the cache.`,

	"doc": "The header line reports the contract's own state, not a runtime measurement: `pacto doc` reads a bundle and never observes a cluster. " +
		"A contract that has never been runtime-evaluated therefore reads `status NotEvaluated`, and one that declares no workload reads `compliance REFERENCE`. " +
		"Both are the expected result for a freshly scaffolded contract — see [Compliance states](model.md#compliance-model).\n\n" +
		"Markdown prints to stdout by default. `-o DIR` writes `DIR/<service>.md`. `-o NAME.html` writes a self-contained static documentation site (a directory) that reuses the dashboard UI offline.\n\n`--serve` serves that static site locally. `--ui swagger` launches an interactive API explorer.\n\n`--serve`, `--ui` and `-o` are mutually exclusive. Use `--interface` to pick one OpenAPI interface with `--ui`. `--target` and `--target iface=url` point try-it-out at a backend.\n\nSibling dependencies are resolved in parallel. OCI bundles cache under `~/.cache/pacto/oci/`. `--no-cache` bypasses the cache.",

	"login": "Credentials are stored in `~/.config/pacto/config.json` (or `$XDG_CONFIG_HOME/pacto/config.json`), keeping them separate from Docker's configuration.\n\n" +
		"### GitHub Container Registry (ghcr.io)\n\n" +
		"For GitHub registries (`ghcr.io` and `docker.pkg.github.com`), pacto can automatically reuse credentials from the [GitHub CLI](https://cli.github.com/) — no `pacto login` required.\n\n" +
		"If you already have `gh` installed and authenticated, pacto will use `gh auth token` to obtain a token transparently. To verify your setup:\n\n" +
		"```bash\n# Check if gh is authenticated\ngh auth status\n\n# Verify the token is available\ngh auth token\n```\n\n" +
		"To push container images or packages, your token needs the `write:packages` scope. If you authenticated `gh` without it, refresh your scopes:\n\n" +
		"```bash\ngh auth refresh --scopes write:packages\n```\n\n" +
		"After this, `pacto push oci://ghcr.io/...` will work without any additional login step.\n\n" +
		"If `gh` is not installed or not authenticated, pacto silently falls back to the next credential source in the chain.",

	"update": "!!! note\n    `pacto update` is not available on dev builds. If you built from source without version injection, install a release build first.\n\n" +
		"### Update notifications\n\n" +
		"When a newer version is available, pacto displays a notification after any command:\n\n" +
		"```\nA new version of pacto is available: v1.0.0 -> v1.2.0\nRun 'pacto update' to update.\n```\n\n" +
		"The check runs asynchronously and adds no latency. Results are cached for 24 hours in `~/.config/pacto/update-check.json`.\n\n" +
		"Notifications are suppressed when:\n\n" +
		"- Running a dev build\n" +
		"- Using `--output-format json` or `--output-format markdown` (the notice shows only for text output)\n" +
		"- The `PACTO_NO_UPDATE_CHECK=1` environment variable is set",

	"dashboard": "It auto-detects sources: pass OCI repositories as arguments, or run it next to the operator (with a kubeconfig) and it discovers OCI repositories from each Pacto resource's `status.contract.resolvedRef`. Use `--no-cache` for a cold start (it skips scanning pre-existing cached bundles; bundles fetched during the session are still cached), and `--diagnostics` to expose the `/api/debug/*` endpoints.\n\n" +
		"For the source model, contract-first merge priority (`local` > `oci` > `cache`) and version-tracking design, see [Dashboard architecture](dashboard-architecture.md). For a tour of what the dashboard surfaces, see [For platform engineers](platform-engineers.md); to run it as a container, see [Dashboard container](dashboard-docker.md).",

	"mcp": "The **default** server exposes the four authoring tools below. Three flags select a different server, each with its own tools -- see [Server modes](#server-modes) immediately after this table:\n\n" +
		"| Tool | Description |\n" +
		"|------|-------------|\n" +
		"| `pacto_create` | Create a new contract from intent-level inputs (name, description, interfaces, runtime semantics). Supports dry run. |\n" +
		"| `pacto_edit` | Edit an existing contract — add/remove interfaces and dependencies, change runtime, update metadata. Supports dry run. |\n" +
		"| `pacto_check` | Validate a contract and return errors, warnings, and actionable improvement suggestions. |\n" +
		"| `pacto_schema` | Return the Pacto format explanation and full JSON Schema reference. |\n\n" +
		"These four authoring tools operate on local contract directories (they read and write `pacto.yaml` on disk) and do not resolve `oci://` refs.\n\n" +
		"### Server modes\n\n" +
		"The default server exposes the authoring tools above. Three flags select a different server instead, and they cannot be combined — passing more than one is an error, never a silent choice:\n\n" +
		"| Invocation | Server |\n" +
		"|------------|--------|\n" +
		"| `pacto mcp` | Authoring tools. |\n" +
		"| `pacto mcp <bundle-ref>` | Authoring tools plus the bundle's OpenAPI operations as executable agent tools, alongside a `pacto_skill` tool for any bundled skills. |\n" +
		"| `pacto mcp --fleet` | Authoring tools plus read-only [operational-graph](operational-graph.md) query tools. |\n" +
		"| `pacto mcp --root <ref> [--root <ref>]` | A read-only contract catalog discovered from the named roots, and nothing else: catalog mode registers no authoring tools, so nothing reachable in it writes to disk. |\n\n" +
		"`--root` is repeatable and takes a local bundle directory or an `oci://` reference. The roots and their dependency closure are resolved once, at startup, through the same reference parsing, credentials and cache the rest of the CLI uses; after that the session is frozen, so a tag that moves in a registry does not change any answer. Roots that do not resolve stay visible with a classified reason and the catalog reports itself as partial. Nothing is crawled, nothing is refreshed and nothing is persisted.\n\n" +
		"See [MCP Integration](mcp-integration.md) for detailed setup with Claude and other AI tools, [Agent capabilities](mcp-integration.md#agent-capabilities) for serving a bundle's operations as tools, and [Contract catalog discovery](mcp-integration.md#contract-catalog-discovery) for the catalog surface.",
}

func main() {
	outputPath := filepath.Join("docs", "cli-reference.md")
	if len(os.Args) > 1 {
		outputPath = os.Args[1]
	}

	keychain := oci.NewKeychain(oci.CredentialOptions{})
	store := oci.NewCachedStore(oci.NewClient(keychain))
	svc := app.NewService(store, &plugin.SubprocessRunner{})
	root := cli.NewRootCommand(svc, cli.VersionInfo{Version: "dev"})

	// Cobra materialises its built-in `completion` command inside ExecuteC, which
	// gendocs never calls — so without this the reference silently omits a command
	// `pacto --help` advertises.
	root.InitDefaultCompletionCmd()

	root.DisableAutoGenTag = true
	walk(root, func(cmd *cobra.Command) { cmd.DisableAutoGenTag = true })

	var buf bytes.Buffer
	buf.WriteString(frontMatter)

	// Generate the root command docs for global flags.
	var rootBuf bytes.Buffer
	if err := doc.GenMarkdownCustom(root, &rootBuf, noLink); err != nil {
		fmt.Fprintf(os.Stderr, "error generating root docs: %v\n", err)
		os.Exit(1)
	}
	sections := parseSections(rootBuf.String())
	buf.WriteString("## Global flags\n\n")
	if opts, ok := sections["Options"]; ok {
		buf.WriteString(opts)
		buf.WriteString("\n")
	}
	buf.WriteString("\n---\n\n")

	// Exit codes (static section). Cross-cutting and needed before any single
	// command's section, because no command's own note can say that the code
	// space is only {0,1} and therefore ambiguous.
	buf.WriteString(exitCodes)

	// OCI version resolution (static section).
	buf.WriteString(ociVersionResolution)

	// Generate docs for each subcommand and its own subcommands. A container
	// command whose only documented flag is --help is a reader dead end, so the
	// walk is recursive: `pacto fleet get` gets a section of its own.
	for _, cmd := range root.Commands() {
		if !cmd.IsAvailableCommand() || cmd.IsAdditionalHelpTopicCommand() {
			continue
		}
		emitCommand(&buf, cmd, cmd.Name(), 0)
		buf.WriteString("---\n\n")
	}

	// Remove the trailing "---\n\n" from the last command since footer starts with one.
	output := buf.String()
	output = strings.TrimSuffix(output, "---\n\n")
	buf.Reset()
	buf.WriteString(output)
	buf.WriteString(footer)

	// Escape the placeholders last, over the finished document, so every source
	// of prose on this page -- cobra help text, commandNotes, frontMatter and
	// footer -- goes through it.
	final := escapePlaceholders(buf.String())
	buf.Reset()
	buf.WriteString(final)

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outputPath)
}

func noLink(s string) string { return "" }

// placeholderTag matches a bare `<name>`, which a browser reads as an unknown
// HTML element and renders as nothing at all. Help text is full of them --
// `<keyId>.pub`, `oci://<repo>@sha256:<digest>` -- and inside a fenced block or a
// code span Markdown escapes them for us. In prose it does not, so the reference
// page silently published `oci://@sha256:` as the required format and told the
// reader to write the private seed to `.key`.
//
// The escaping happens here, on the generated page, and not in the help strings
// themselves: the same text is printed to a terminal by `--help`, where
// `&lt;keyId&gt;` would be the wrong thing to show.
var placeholderTag = regexp.MustCompile(`<([A-Za-z][A-Za-z0-9._-]*)>`)

// escapePlaceholders escapes every placeholderTag that is outside a fenced code
// block and outside an inline code span, leaving the rest byte-identical.
func escapePlaceholders(md string) string {
	lines := strings.Split(md, "\n")
	inFence := false
	for i, line := range lines {
		if t := strings.TrimSpace(line); strings.HasPrefix(t, "```") || strings.HasPrefix(t, "~~~") {
			inFence = !inFence
			continue
		}
		if inFence || !strings.Contains(line, "<") {
			continue
		}
		// Split on backticks: even segments are prose, odd ones are code spans.
		// An unbalanced backtick leaves the tail treated as code, which errs
		// towards changing nothing.
		parts := strings.Split(line, "`")
		for j := 0; j < len(parts); j += 2 {
			parts[j] = placeholderTag.ReplaceAllString(parts[j], "&lt;$1&gt;")
		}
		lines[i] = strings.Join(parts, "`")
	}
	return strings.Join(lines, "\n")
}

// walk applies fn to cmd and every command beneath it.
func walk(cmd *cobra.Command, fn func(*cobra.Command)) {
	fn(cmd)
	for _, sub := range cmd.Commands() {
		walk(sub, fn)
	}
}

// noRecurse names containers whose children add no Pacto-specific surface.
// `completion` is cobra's built-in and its four shell subcommands are byte-for-byte
// the same in every cobra CLI, so the reference documents the parent and leaves the
// shells to `pacto completion --help`.
var noRecurse = map[string]bool{"completion": true}

// emitCommand writes cmd's section, then recurses into its subcommands. path is
// the command words after "pacto"; depth 0 is a top-level command.
func emitCommand(buf *bytes.Buffer, cmd *cobra.Command, path string, depth int) {
	var cmdBuf bytes.Buffer
	if err := doc.GenMarkdownCustom(cmd, &cmdBuf, noLink); err != nil {
		fmt.Fprintf(os.Stderr, "error generating docs for %s: %v\n", path, err)
		os.Exit(1)
	}
	buf.WriteString(formatCommand(cmd, path, cmdBuf.String(), depth))

	if noRecurse[cmd.Name()] {
		return
	}
	for _, sub := range cmd.Commands() {
		if !sub.IsAvailableCommand() || sub.IsAdditionalHelpTopicCommand() {
			continue
		}
		emitCommand(buf, sub, path+" "+sub.Name(), depth+1)
	}
}

// parseSections splits cobra-generated markdown into named sections.
// Section names are the H3 headings (e.g. "Synopsis", "Examples", "Options").
func parseSections(md string) map[string]string {
	sections := make(map[string]string)
	lines := strings.Split(md, "\n")

	var currentSection string
	var content strings.Builder

	for _, line := range lines {
		if heading, ok := strings.CutPrefix(line, "### "); ok {
			if currentSection != "" {
				sections[currentSection] = strings.TrimSpace(content.String())
			}
			currentSection = strings.TrimSpace(heading)
			content.Reset()
			continue
		}
		// Skip the top-level ## heading line.
		if strings.HasPrefix(line, "## ") {
			continue
		}
		if currentSection != "" {
			content.WriteString(line)
			content.WriteString("\n")
		}
	}
	if currentSection != "" {
		sections[currentSection] = strings.TrimSpace(content.String())
	}

	return sections
}

// formatCommand converts cobra-generated markdown for a subcommand into the
// desired format for the CLI reference page. depth sets the heading level, so a
// subcommand nests under its parent rather than competing with it.
func formatCommand(cmd *cobra.Command, path, md string, depth int) string {
	sections := parseSections(md)
	var sb strings.Builder

	fmt.Fprintf(&sb, "%s `pacto %s`\n\n", strings.Repeat("#", depth+2), path)

	// Write the description from Synopsis section.
	var desc, usage string
	if synopsis, ok := sections["Synopsis"]; ok {
		// Synopsis contains: description lines, then a code block with usage.
		parts := strings.SplitN(synopsis, "```", 3)
		desc = strings.TrimSpace(parts[0])
		if len(parts) >= 3 {
			usage = strings.TrimSpace(parts[1])
		}
	}
	// Cobra puts Short above the Synopsis heading and only repeats it inside when
	// Long is set, so a command with no Long would otherwise render as a bare
	// heading and a --help flag. Fall back to what `pacto <cmd> --help` shows.
	if desc == "" {
		desc = strings.TrimSpace(cmd.Short)
	}
	if usage == "" {
		usage = strings.TrimSpace(cmd.UseLine())
	}
	if desc != "" {
		sb.WriteString(desc)
		sb.WriteString("\n\n")
	}
	if usage != "" {
		sb.WriteString("```\n")
		sb.WriteString(usage)
		sb.WriteString("\n```\n")
	}

	// Write examples.
	if examples, ok := sections["Examples"]; ok {
		sb.WriteString("\n**Examples:**\n\n")
		sb.WriteString(examples)
		sb.WriteString("\n")
	}

	// Write command-specific flags (not inherited global flags).
	if opts, ok := sections["Options"]; ok {
		sb.WriteString("\n**Flags:**\n\n")
		sb.WriteString(opts)
		sb.WriteString("\n")
	}

	// Append additional notes for this command.
	if note, ok := commandNotes[path]; ok {
		sb.WriteString("\n")
		sb.WriteString(note)
		sb.WriteString("\n")
	}

	sb.WriteString("\n")
	return sb.String()
}
