#!/usr/bin/env bash
# Regenerate the guided tour's terminal transcripts (`make gen-demo-transcripts`).
#
# The docs gate only executes fenced YAML, so a bash fence in docs/ is held true
# by nothing. The tour does not transcribe its output: it runs the beats here and
# includes the bytes, and docs-check compares the result against the committed
# tree — so a change in what `pacto` prints fails the same gate that guards the
# CLI reference.
#
# Offline and deterministic by construction: every beat reads the committed demo
# fixture and nothing else. Beats 11 and 12 are not here — one needs a stdin
# handshake, the other a live dashboard — so the tour writes those two inline.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
# shellcheck source=../../examples/demo/beats.sh
. examples/demo/beats.sh

OUT="examples/demo/generated"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
BIN="$WORK/pacto"
go build -o "$BIN" ./cmd/pacto

mkdir -p "$OUT"
# Drop transcripts from a previous beat numbering first. The tour snippet-includes
# by name, so an orphan left behind here is invisible to the drift gate — it stays
# byte-identical to itself forever while matching no beat.
rm -f "$OUT"/_beat-*.md

# emit <basename> <beat>...  — one transcript file, one bash+console pair per beat.
emit() {
  file="$OUT/$1"; shift
  printf '<!-- Generated by release/scripts/gen_demo_transcripts.sh. Do not edit. -->\n' >"$file"
  for beat in "$@"; do
    args="$(beat_args "$beat")"
    printf '\n```bash\npacto %s\n```\n\n```console\n' "$args" >>"$file"
    # Both streams, and a non-zero exit is not a failure: `pacto diff` and
    # `pacto impact` exit 1 when they refuse a change, and that refusal is the
    # beat. Capture what the terminal shows either way.
    # shellcheck disable=SC2086
    "$BIN" $args >>"$file" 2>&1 || true
    printf '```\n' >>"$file"
  done
}

emit _beat-01.md 1
emit _beat-02.md 2
emit _beat-03.md 3 3-readiness
emit _beat-04.md 4
emit _beat-05.md 5
emit _beat-06.md 6
emit _beat-07.md 7
emit _beat-08.md 8
emit _beat-09.md 9
emit _beat-10.md 10

echo "==> wrote $(ls "$OUT" | wc -l | tr -d ' ') transcripts to $OUT"
