package doc

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"regexp"
	"sort"
	"strings"

	"github.com/trianalab/pacto/internal/graph"
	"github.com/trianalab/pacto/internal/validation"
	"github.com/trianalab/pacto/pkg/contract"
)

// schemaDescriptions maps "path.enumValue" to its x-enum-descriptions text.
// Populated at init from the embedded JSON Schema.
var schemaDescriptions map[string]string

func init() {
	schemaDescriptions = loadSchemaDescriptions(validation.SchemaBytes())
}

func loadSchemaDescriptions(data []byte) map[string]string {
	dst := make(map[string]string)
	var root map[string]interface{}
	if err := json.Unmarshal(data, &root); err != nil {
		return dst
	}
	props, _ := root["properties"].(map[string]interface{})
	extractEnumDescriptions(props, "", dst)
	return dst
}

// extractEnumDescriptions recursively walks schema properties and collects
// x-enum-descriptions into the dst map keyed as "path.value".
func extractEnumDescriptions(props map[string]interface{}, prefix string, dst map[string]string) {
	for key, val := range props {
		obj, ok := val.(map[string]interface{})
		if !ok {
			continue
		}
		path := key
		if prefix != "" {
			path = prefix + "." + key
		}

		// Collect description for this field
		if desc, ok := obj["description"].(string); ok {
			dst[path] = desc
		}

		// Collect x-enum-descriptions
		if xDescs, ok := obj["x-enum-descriptions"].(map[string]interface{}); ok {
			for enumVal, enumDesc := range xDescs {
				if s, ok := enumDesc.(string); ok {
					dst[path+"."+enumVal] = s
				}
			}
		}

		// Recurse into nested properties
		if nested, ok := obj["properties"].(map[string]interface{}); ok {
			extractEnumDescriptions(nested, path, dst)
		}
	}
}

// Generate produces a Markdown document from a contract and its bundle filesystem.
// If gr is non-nil, the Mermaid diagram will show the full transitive dependency graph.
func Generate(c *contract.Contract, fsys fs.FS, gr *graph.Result) (string, error) {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s\n\n", c.Service.Name)
	writeDescription(&b, c)
	writeTableOfContents(&b, c)
	writeMermaidDiagram(&b, c, gr)
	writeInterfaces(&b, c, fsys)
	writeConfiguration(&b, c, fsys)
	writeDependencies(&b, c)

	fmt.Fprintln(&b, "---")
	fmt.Fprintln(&b)
	writeMetadataFooter(&b, c)
	fmt.Fprintln(&b, "Generated by [Pacto](https://trianalab.github.io/pacto)")
	fmt.Fprintln(&b)

	return b.String(), nil
}

// schemaDesc looks up a description from the embedded schema.
// path is a dot-separated key like "runtime.state.type.stateful".
func schemaDesc(path string) string {
	return schemaDescriptions[path]
}

type conceptRow struct{ concept, value, desc string }

func writeDescription(b *strings.Builder, c *contract.Contract) {
	sentence := buildSummaryParagraph(c)
	fmt.Fprintln(b, sentence)
	fmt.Fprintln(b)

	rows := buildConceptRows(c)
	if len(rows) > 0 {
		fmt.Fprintln(b, "| Concept | Value | Description |")
		fmt.Fprintln(b, "|---------|-------|-------------|")
		for _, r := range rows {
			fmt.Fprintf(b, "| **%s** | `%s` | %s |\n", r.concept, r.value, r.desc)
		}
		fmt.Fprintln(b)
	}

	fmt.Fprintln(b, "For more information on contract concepts, see the [Contract Reference](https://trianalab.github.io/pacto/contract-reference/).")
	fmt.Fprintln(b)
}

func buildSummaryParagraph(c *contract.Contract) string {
	parts := []string{fmt.Sprintf("**%s** `v%s` is a `%s` `%s` workload", c.Service.Name, c.Service.Version, c.Runtime.State.Type, c.Runtime.Workload)}
	if len(c.Interfaces) > 0 {
		noun := "interface"
		if len(c.Interfaces) > 1 {
			noun = "interfaces"
		}
		parts = append(parts, fmt.Sprintf("exposing %d %s", len(c.Interfaces), noun))
	}
	if len(c.Dependencies) > 0 {
		noun := "dependency"
		if len(c.Dependencies) > 1 {
			noun = "dependencies"
		}
		parts = append(parts, fmt.Sprintf("with %d %s", len(c.Dependencies), noun))
	}
	sentence := strings.Join(parts, " ") + "."

	var details []string
	if c.Service.Owner != "" {
		details = append(details, fmt.Sprintf("owned by `%s`", c.Service.Owner))
	}
	if c.Service.Image != nil {
		details = append(details, fmt.Sprintf("packaged as `%s`", c.Service.Image.Ref))
	}
	if c.Scaling != nil {
		details = append(details, fmt.Sprintf("scales from `%d` to `%d` replicas", c.Scaling.Min, c.Scaling.Max))
	}
	if len(details) > 0 {
		sentence += " " + capitalizeFirst(strings.Join(details, ", ")) + "."
	}
	return sentence
}

func buildConceptRows(c *contract.Contract) []conceptRow {
	var rows []conceptRow

	// Workload and state type
	schemaRows := []struct {
		concept, path, value string
	}{
		{"Workload", "runtime.workload." + c.Runtime.Workload, c.Runtime.Workload},
		{"State", "runtime.state.type." + c.Runtime.State.Type, c.Runtime.State.Type},
	}
	for _, sr := range schemaRows {
		if desc := schemaDesc(sr.path); desc != "" {
			rows = append(rows, conceptRow{sr.concept, sr.value, capitalizeFirst(desc)})
		}
	}

	// Persistence rows (only when values are set)
	rows = appendPersistenceRows(rows, c)

	// Data criticality
	if desc := schemaDesc("runtime.state.dataCriticality." + c.Runtime.State.DataCriticality); desc != "" {
		rows = append(rows, conceptRow{"Data criticality", c.Runtime.State.DataCriticality, capitalizeFirst(desc)})
	}

	// Lifecycle rows
	rows = appendLifecycleRows(rows, c)

	return rows
}

func appendPersistenceRows(rows []conceptRow, c *contract.Contract) []conceptRow {
	if scope := c.Runtime.State.Persistence.Scope; scope != "" {
		if desc := schemaDesc("runtime.state.persistence.scope." + scope); desc != "" {
			rows = append(rows, conceptRow{"Persistence scope", scope, capitalizeFirst(desc)})
		}
	}
	if dur := c.Runtime.State.Persistence.Durability; dur != "" {
		if desc := schemaDesc("runtime.state.persistence.durability." + dur); desc != "" {
			rows = append(rows, conceptRow{"Persistence durability", dur, capitalizeFirst(desc)})
		}
	}
	return rows
}

func appendLifecycleRows(rows []conceptRow, c *contract.Contract) []conceptRow {
	if c.Runtime.Lifecycle == nil {
		return rows
	}
	if c.Runtime.Lifecycle.UpgradeStrategy != "" {
		if desc := schemaDesc("runtime.lifecycle.upgradeStrategy." + c.Runtime.Lifecycle.UpgradeStrategy); desc != "" {
			rows = append(rows, conceptRow{"Upgrade strategy", c.Runtime.Lifecycle.UpgradeStrategy, capitalizeFirst(desc)})
		}
	}
	if c.Runtime.Lifecycle.GracefulShutdownSeconds != nil {
		rows = append(rows, conceptRow{"Graceful shutdown", fmt.Sprintf("%ds", *c.Runtime.Lifecycle.GracefulShutdownSeconds), "Time allowed for in-flight requests to complete before termination"})
	}
	return rows
}

func writeTableOfContents(b *strings.Builder, c *contract.Contract) {
	fmt.Fprintln(b, "## Table of Contents")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "- [Architecture](#architecture)")
	if len(c.Interfaces) > 0 {
		fmt.Fprintln(b, "- [Interfaces](#interfaces)")
		for _, iface := range c.Interfaces {
			heading := interfaceHeading(iface)
			anchor := strings.ToLower(heading)
			anchor = strings.ReplaceAll(anchor, " ", "-")
			anchor = strings.ReplaceAll(anchor, ":", "")
			fmt.Fprintf(b, "  - [%s](#%s)\n", heading, anchor)
		}
	}
	if c.Configuration != nil && c.Configuration.Schema != "" {
		fmt.Fprintln(b, "- [Configuration](#configuration)")
	}
	if len(c.Dependencies) > 0 {
		fmt.Fprintln(b, "- [Dependencies](#dependencies)")
	}
	fmt.Fprintln(b)
}

var nonAlphanumeric = regexp.MustCompile(`[^a-zA-Z0-9]`)

func sanitizeMermaidID(s string) string {
	return nonAlphanumeric.ReplaceAllString(s, "")
}

func depName(ref string) string {
	// Strip tag or digest suffix
	name := ref
	if i := strings.LastIndex(name, "@"); i != -1 {
		name = name[:i]
	}
	if i := strings.LastIndex(name, ":"); i != -1 {
		name = name[:i]
	}
	// Extract last path component
	if i := strings.LastIndex(name, "/"); i != -1 {
		name = name[i+1:]
	}
	return name
}

func writeMermaidDiagram(b *strings.Builder, c *contract.Contract, gr *graph.Result) {
	fmt.Fprintln(b, "## Architecture")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "```mermaid")
	fmt.Fprintln(b, "graph LR")

	allContracts := collectAllContracts(c, gr)

	hasPublic := anyPublicInterface(allContracts)
	if hasPublic {
		fmt.Fprintln(b, "  external([\"External User\"])")
		fmt.Fprintln(b)
	}

	for _, sc := range allContracts {
		writeServiceSubgraph(b, sc, hasPublic)
	}

	writeDependencyEdges(b, c, gr)

	fmt.Fprintln(b, "```")
	fmt.Fprintln(b)
}

func collectAllContracts(c *contract.Contract, gr *graph.Result) []*contract.Contract {
	all := []*contract.Contract{c}
	if gr != nil && gr.Root != nil {
		for _, node := range collectUniqueNodes(gr.Root) {
			if node.Contract != nil {
				all = append(all, node.Contract)
			}
		}
	}
	return all
}

func anyPublicInterface(contracts []*contract.Contract) bool {
	for _, sc := range contracts {
		for _, iface := range sc.Interfaces {
			if iface.Visibility == contract.VisibilityPublic {
				return true
			}
		}
	}
	return false
}

func writeDependencyEdges(b *strings.Builder, c *contract.Contract, gr *graph.Result) {
	if gr != nil && gr.Root != nil && len(gr.Root.Dependencies) > 0 {
		fmt.Fprintln(b)
		writeMermaidEdges(b, gr.Root)
		return
	}
	if len(c.Dependencies) == 0 {
		return
	}
	fmt.Fprintln(b)
	svcID := sanitizeMermaidID(c.Service.Name)
	for _, dep := range c.Dependencies {
		name := depName(dep.Ref)
		depID := "dep_" + sanitizeMermaidID(name)
		if dep.Required {
			fmt.Fprintf(b, "  %s -->|\"required · %s\"| %s[\"%s\"]\n", svcID, dep.Compatibility, depID, name)
		} else {
			fmt.Fprintf(b, "  %s -.->|\"optional · %s\"| %s[\"%s\"]\n", svcID, dep.Compatibility, depID, name)
		}
	}
}

func writeServiceSubgraph(b *strings.Builder, c *contract.Contract, hasExternal bool) {
	svcID := sanitizeMermaidID(c.Service.Name)
	svcLabel := fmt.Sprintf("%s v%s", c.Service.Name, c.Service.Version)
	fmt.Fprintf(b, "  subgraph %s[\"%s\"]\n", svcID, svcLabel)
	fmt.Fprintln(b, "    direction TB")
	stateLabel := fmt.Sprintf("%s · %s criticality", c.Runtime.State.Type, c.Runtime.State.DataCriticality)
	if c.Runtime.State.Persistence.Scope != "" {
		stateLabel += fmt.Sprintf(" · %s %s", c.Runtime.State.Persistence.Scope, c.Runtime.State.Persistence.Durability)
	}
	if c.Scaling != nil {
		stateLabel += fmt.Sprintf(" · %d–%d replicas", c.Scaling.Min, c.Scaling.Max)
	}
	fmt.Fprintf(b, "    %s_state[(\"%s\")]\n", svcID, stateLabel)

	// Interface nodes inside the subgraph
	for _, iface := range c.Interfaces {
		nodeID := svcID + "_iface_" + sanitizeMermaidID(iface.Name)
		label := iface.Name + "<br/>" + iface.Type
		if iface.Port != nil {
			label += fmt.Sprintf(" :%d", *iface.Port)
		}
		if iface.Visibility != "" {
			label += "<br/>" + iface.Visibility
		}
		if iface.Name == c.Runtime.Health.Interface {
			label += "<br/>♥ health"
		}
		fmt.Fprintf(b, "    %s[\"%s\"]\n", nodeID, label)
	}

	fmt.Fprintln(b, "  end")
	fmt.Fprintln(b)

	// External user arrows to public interfaces
	for _, iface := range c.Interfaces {
		if hasExternal && iface.Visibility == contract.VisibilityPublic {
			nodeID := svcID + "_iface_" + sanitizeMermaidID(iface.Name)
			fmt.Fprintf(b, "  external --> %s\n", nodeID)
		}
	}
}

func collectUniqueNodes(root *graph.Node) []*graph.Node {
	var nodes []*graph.Node
	seen := map[string]bool{}
	walkCollectNodes(root, seen, &nodes)
	return nodes
}

func walkCollectNodes(node *graph.Node, seen map[string]bool, nodes *[]*graph.Node) {
	if node == nil {
		return
	}
	for _, edge := range node.Dependencies {
		if edge.Node == nil || edge.Shared || seen[edge.Node.Name] {
			continue
		}
		seen[edge.Node.Name] = true
		*nodes = append(*nodes, edge.Node)
		walkCollectNodes(edge.Node, seen, nodes)
	}
}

func writeMermaidEdges(b *strings.Builder, node *graph.Node) {
	seen := map[string]bool{}
	walkMermaidEdges(b, node, seen)
}

func walkMermaidEdges(b *strings.Builder, node *graph.Node, seen map[string]bool) {
	if node == nil {
		return
	}
	for _, edge := range node.Dependencies {
		if edge.Node == nil {
			continue
		}
		key := node.Name + "-->" + edge.Node.Name
		if seen[key] {
			continue
		}
		seen[key] = true
		fmt.Fprintf(b, "  %s --> %s\n", node.Name, edge.Node.Name)
		if !edge.Shared {
			walkMermaidEdges(b, edge.Node, seen)
		}
	}
}

func writeInterfaces(b *strings.Builder, c *contract.Contract, fsys fs.FS) {
	if len(c.Interfaces) == 0 {
		return
	}

	fmt.Fprintln(b, "## Interfaces")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Name | Type | Port | Visibility |")
	fmt.Fprintln(b, "|------|------|------|------------|")

	for _, iface := range c.Interfaces {
		port := "\u2014"
		if iface.Port != nil {
			port = fmt.Sprintf("`%d`", *iface.Port)
		}
		vis := "\u2014"
		if iface.Visibility != "" {
			vis = fmt.Sprintf("`%s`", iface.Visibility)
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n", iface.Name, iface.Type, port, vis)
	}
	fmt.Fprintln(b)

	// Detail subsections for each interface
	for _, iface := range c.Interfaces {
		if iface.Type == contract.InterfaceTypeHTTP {
			writeHTTPInterfaceDetail(b, iface, c.Runtime.Health, fsys)
		} else {
			writeNonHTTPInterfaceDetail(b, iface, c.Runtime.Health)
		}
	}
}

func writeConfiguration(b *strings.Builder, c *contract.Contract, fsys fs.FS) {
	if c.Configuration == nil || c.Configuration.Schema == "" {
		return
	}

	props, err := readSchemaProperties(fsys, c.Configuration.Schema)
	if err != nil {
		fmt.Fprintln(b, "## Configuration")
		fmt.Fprintln(b)
		fmt.Fprintf(b, "_Could not read configuration schema: %v_\n\n", err)
		return
	}

	if len(props) == 0 {
		return
	}

	fmt.Fprintln(b, "## Configuration")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Property | Type | Description | Default | Required |")
	fmt.Fprintln(b, "|----------|------|-------------|---------|----------|")

	for _, p := range props {
		def := "\u2014"
		if p.Default != "" {
			def = fmt.Sprintf("`%s`", p.Default)
		}
		req := "No"
		if p.Required {
			req = "Yes"
		}
		desc := p.Description
		if desc == "" {
			desc = "\u2014"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s | %s |\n", p.Name, p.Type, desc, def, req)
	}
	fmt.Fprintln(b)
}

func interfaceHeading(iface contract.Interface) string {
	switch iface.Type {
	case contract.InterfaceTypeHTTP:
		return fmt.Sprintf("HTTP Interface: %s", iface.Name)
	case contract.InterfaceTypeGRPC:
		return fmt.Sprintf("gRPC Interface: %s", iface.Name)
	case contract.InterfaceTypeEvent:
		return fmt.Sprintf("Event Interface: %s", iface.Name)
	default:
		return fmt.Sprintf("%s Interface: %s", capitalizeFirst(iface.Type), iface.Name)
	}
}

func healthSuffix(ifaceName string, health contract.Health) string {
	if health.Interface != ifaceName {
		return ""
	}
	var parts []string
	if health.Path != "" {
		parts = append(parts, fmt.Sprintf("owns the health path under `%s`", health.Path))
	}
	if health.InitialDelaySeconds != nil {
		parts = append(parts, fmt.Sprintf("requires an initial delay of `%ds`", *health.InitialDelaySeconds))
	}
	if len(parts) > 0 {
		return " It " + strings.Join(parts, " and ") + "."
	}
	return ""
}

func writeInterfaceSentence(iface contract.Interface) string {
	s := fmt.Sprintf("The `%s` interface", iface.Name)
	if iface.Visibility != "" && iface.Port != nil {
		s += fmt.Sprintf(" is `%s` and exposes port `%d`", iface.Visibility, *iface.Port)
	} else if iface.Visibility != "" {
		s += fmt.Sprintf(" is `%s`", iface.Visibility)
	} else if iface.Port != nil {
		s += fmt.Sprintf(" exposes port `%d`", *iface.Port)
	}
	return s
}

func writeHTTPInterfaceDetail(b *strings.Builder, iface contract.Interface, health contract.Health, fsys fs.FS) {
	fmt.Fprintf(b, "### %s\n\n", interfaceHeading(iface))
	fmt.Fprintf(b, "%s.%s\n\n", writeInterfaceSentence(iface), healthSuffix(iface.Name, health))

	if iface.Contract == "" {
		return
	}

	endpoints, err := readOpenAPIEndpoints(fsys, iface.Contract)
	if err != nil {
		fmt.Fprintf(b, "_Could not read OpenAPI spec: %v_\n\n", err)
		return
	}

	if len(endpoints) == 0 {
		return
	}

	fmt.Fprintln(b, "#### Endpoints")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Method | Path | Summary |")
	fmt.Fprintln(b, "|--------|------|---------|")

	for _, ep := range endpoints {
		summary := ep.Summary
		if summary == "" {
			summary = "\u2014"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", strings.ToUpper(ep.Method), ep.Path, summary)
	}
	fmt.Fprintln(b)
}

func writeNonHTTPInterfaceDetail(b *strings.Builder, iface contract.Interface, health contract.Health) {
	fmt.Fprintf(b, "### %s\n\n", interfaceHeading(iface))

	desc := writeInterfaceSentence(iface)
	if iface.Contract != "" {
		desc += fmt.Sprintf(". Its contract is defined in `%s`", iface.Contract)
	}
	fmt.Fprintf(b, "%s.%s\n\n", desc, healthSuffix(iface.Name, health))
}

func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func writeDependencies(b *strings.Builder, c *contract.Contract) {
	if len(c.Dependencies) == 0 {
		return
	}

	fmt.Fprintln(b, "## Dependencies")
	fmt.Fprintln(b)
	fmt.Fprintln(b, "| Reference | Compatibility | Required |")
	fmt.Fprintln(b, "|-----------|---------------|----------|")

	for _, dep := range c.Dependencies {
		req := "No"
		if dep.Required {
			req = "Yes"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", dep.Ref, dep.Compatibility, req)
	}
	fmt.Fprintln(b)
}

func writeMetadataFooter(b *strings.Builder, c *contract.Contract) {
	if len(c.Metadata) == 0 {
		return
	}

	keys := make([]string, 0, len(c.Metadata))
	for k := range c.Metadata {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		fmt.Fprintf(b, "`%s: %v` ", k, c.Metadata[k])
	}
	fmt.Fprintln(b)
	fmt.Fprintln(b)
}
