// Package doc generates Markdown documentation from a dashboard service snapshot
// and serves it as rendered HTML. The generated docs include an at-a-glance
// summary, a runtime & operations table, a Mermaid architecture diagram,
// interface and endpoint tables, configuration and policy tables, the dependency
// graph, and readiness, SBOM and lockfile sections. The snapshot
// (dashboard.ServiceDetails) is the single source of truth already used by the
// dashboard, so the doc and the UI stay in lock-step.
package doc

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/trianalab/pacto/v2/pkg/contract"
	"github.com/trianalab/pacto/v2/pkg/dashboard"
	"github.com/trianalab/pacto/v2/pkg/graph"
)

// sectionNumberer tracks hierarchical section numbers (1, 1.1, 1.1.1, etc.).
type sectionNumberer struct {
	counters []int
}

// Next increments the counter at the given depth (1-based) and returns the
// full section number string. Deeper levels are reset when a shallower level
// is incremented.
func (n *sectionNumberer) Next(depth int) string {
	for len(n.counters) < depth {
		n.counters = append(n.counters, 0)
	}
	n.counters = n.counters[:depth]
	n.counters[depth-1]++
	parts := make([]string, depth)
	for i, v := range n.counters {
		parts[i] = strconv.Itoa(v)
	}
	return strings.Join(parts, ".")
}

// Generate renders a Markdown document from a dashboard service snapshot.
// gr (may be nil) drives the Mermaid architecture diagram and the per-dependency
// snapshots via the existing graph-walk helpers; when it is nil the diagram is
// built from the snapshot alone.
func Generate(d *dashboard.ServiceDetails, gr *graph.Result) (string, error) {
	var b strings.Builder
	num := &sectionNumberer{}

	fmt.Fprintf(&b, "# %s\n\n", d.Name)
	writeSnapshotSummary(&b, d)
	writeTableOfContents(&b, d)
	writeRuntimeOps(&b, d, num)
	writeMermaidDiagram(&b, gr, d, num)
	writeInterfaces(&b, d, num)
	writeConfiguration(&b, d, num)
	writePolicies(&b, d, num)
	writeDependencies(&b, d, gr, num)
	writeReadiness(&b, d, num)
	writeSBOM(&b, d, num)
	writeLockfile(&b, d, num)
	writeBundleDocs(&b, d, num)

	fmt.Fprintln(&b, "---")
	fmt.Fprintln(&b)
	writeMetadataFooter(&b, d)
	fmt.Fprintln(&b, "Generated by [Pacto](https://trianalab.github.io/pacto)")
	fmt.Fprintln(&b)

	return b.String(), nil
}

// ── §presence + at-a-glance + TOC ──────────────────────────────────────

func hasSBOM(d *dashboard.ServiceDetails) bool {
	return d.SBOM != nil && len(d.SBOM.Packages) > 0
}

func hasLock(d *dashboard.ServiceDetails) bool {
	return d.Lock != nil && d.Lock.Present
}

// sectionTitles returns the ordered titles of the numbered H2 sections that are
// present for this snapshot. The body writers below emit their headings in the
// same order (each guarded by the same presence predicate) so num.Next(1)
// produces exactly these numbers — keeping the TOC anchors in sync with the
// body without a second numberer.
func sectionTitles(d *dashboard.ServiceDetails) []string {
	var titles []string
	if d.Runtime != nil || d.Scaling != nil {
		titles = append(titles, "Runtime & operations")
	}
	titles = append(titles, "Architecture") // always rendered (at least the root subgraph)
	if len(d.Interfaces) > 0 {
		titles = append(titles, "Interfaces")
	}
	if len(d.Configurations) > 0 {
		titles = append(titles, "Configuration")
	}
	if len(d.Policies) > 0 {
		titles = append(titles, "Policies")
	}
	if len(d.Dependencies) > 0 {
		titles = append(titles, "Dependencies")
	}
	if d.Readiness != nil {
		titles = append(titles, "Readiness")
	}
	if hasSBOM(d) {
		titles = append(titles, "SBOM")
	}
	if hasLock(d) {
		titles = append(titles, "Lockfile")
	}
	if len(d.Docs) > 0 {
		titles = append(titles, "Documentation")
	}
	return titles
}

func writeSnapshotSummary(b *strings.Builder, d *dashboard.ServiceDetails) {
	fmt.Fprintf(b, "**%s** `v%s`", d.Name, d.Version)
	if d.ContractStatus != "" {
		fmt.Fprintf(b, " · status `%s`", d.ContractStatus)
	}
	if d.Compliance != nil {
		fmt.Fprintf(b, " · compliance `%s`", d.Compliance.Status)
	}
	if d.Readiness != nil {
		fmt.Fprintf(b, " · readiness `%d/100`", d.Readiness.Score)
	}
	fmt.Fprintln(b)
	fmt.Fprintln(b)

	rows := [][2]string{}
	if !d.Owner.IsEmpty() {
		rows = append(rows, [2]string{"Owner", d.Owner.DisplayString()})
	}
	if d.ImageRef != "" {
		rows = append(rows, [2]string{"Image", d.ImageRef})
	}
	if d.ChartRef != "" {
		rows = append(rows, [2]string{"Chart", d.ChartRef})
	}
	if len(rows) > 0 {
		fmt.Fprintln(b, "| Field | Value |")
		fmt.Fprintln(b, "|-------|-------|")
		for _, r := range rows {
			fmt.Fprintf(b, "| **%s** | `%s` |\n", r[0], escapeMarkdownCell(r[1]))
		}
		fmt.Fprintln(b)
	}
}

// headingAnchor generates a markdown-compatible anchor from a heading string.
// It lowercases, replaces spaces with hyphens, and strips colons and dots.
func headingAnchor(s string) string {
	a := strings.ToLower(s)
	a = strings.ReplaceAll(a, " ", "-")
	a = strings.ReplaceAll(a, ":", "")
	a = strings.ReplaceAll(a, ".", "")
	return a
}

func writeTableOfContents(b *strings.Builder, d *dashboard.ServiceDetails) {
	fmt.Fprintln(b, "## Table of Contents")
	fmt.Fprintln(b)
	for i, title := range sectionTitles(d) {
		sec := strconv.Itoa(i + 1)
		fmt.Fprintf(b, "- [%s. %s](#%s)\n", sec, title, headingAnchor(sec+". "+title))
	}
	fmt.Fprintln(b)
}

// ── §1 Runtime & operations ────────────────────────────────────────────

func writeRuntimeOps(b *strings.Builder, d *dashboard.ServiceDetails, num *sectionNumberer) {
	if d.Runtime == nil && d.Scaling == nil {
		return
	}
	fmt.Fprintf(b, "## %s. Runtime & operations\n\n", num.Next(1))
	writeRuntimeTable(b, d)
}

// writeRuntimeTable emits the runtime/scaling Property/Value table body. Shared
// by the root section and the per-dependency detail.
func writeRuntimeTable(b *strings.Builder, d *dashboard.ServiceDetails) {
	fmt.Fprintln(b, "| Property | Value |")
	fmt.Fprintln(b, "|----------|-------|")
	if r := d.Runtime; r != nil {
		writeKV(b, "Workload", r.Workload)
		writeKV(b, "State", r.StateType)
		writeKV(b, "Data criticality", r.DataCriticality)
		writeKV(b, "Persistence scope", r.PersistenceScope)
		writeKV(b, "Persistence durability", r.PersistenceDurability)
		writeKV(b, "Upgrade strategy", r.UpgradeStrategy)
		if r.GracefulShutdownSeconds != nil {
			writeKV(b, "Graceful shutdown", fmt.Sprintf("%ds", *r.GracefulShutdownSeconds))
		}
		writeKV(b, "Health interface", r.HealthInterface)
		writeKV(b, "Health path", r.HealthPath)
		writeKV(b, "Metrics interface", r.MetricsInterface)
		writeKV(b, "Metrics path", r.MetricsPath)
	}
	if s := d.Scaling; s != nil {
		if s.Replicas != nil {
			writeKV(b, "Replicas", fmt.Sprintf("%d", *s.Replicas))
		} else if s.Min != nil || s.Max != nil {
			writeKV(b, "Replicas", fmt.Sprintf("%s–%s", intp(s.Min), intp(s.Max)))
		}
	}
	fmt.Fprintln(b)
}

func writeKV(b *strings.Builder, k, v string) {
	if v == "" {
		return
	}
	fmt.Fprintf(b, "| **%s** | `%s` |\n", k, escapeMarkdownCell(v))
}

func intp(p *int) string {
	if p == nil {
		return "?"
	}
	return strconv.Itoa(*p)
}

// ── §2 Architecture (Mermaid) ──────────────────────────────────────────

func writeMermaidDiagram(b *strings.Builder, gr *graph.Result, d *dashboard.ServiceDetails, num *sectionNumberer) {
	root := rootContract(gr, d)

	fmt.Fprintf(b, "## %s. Architecture\n\n", num.Next(1))
	fmt.Fprintln(b, "```mermaid")
	fmt.Fprintln(b, "graph TB")

	allContracts := collectAllContracts(root, gr)

	hasPublic := anyPublicInterface(allContracts)
	if hasPublic {
		fmt.Fprintln(b, "  external([\"External User\"])")
		fmt.Fprintln(b)
	}

	for _, sc := range allContracts {
		writeServiceSubgraph(b, sc, hasPublic)
	}

	writeDependencyEdges(b, root, gr)

	fmt.Fprintln(b, "```")
	fmt.Fprintln(b)
}

// rootContract returns the root contract for the diagram: the resolved graph
// root when present, otherwise a minimal contract reconstructed from the
// snapshot so the single-service fallback reuses the same subgraph renderers.
func rootContract(gr *graph.Result, d *dashboard.ServiceDetails) *contract.Contract {
	if gr != nil && gr.Root != nil && gr.Root.Contract != nil {
		return gr.Root.Contract
	}
	return contractFromDetails(d)
}

// contractFromDetails rebuilds the subset of a contract the Mermaid diagram
// needs (identity, interfaces, dependencies, runtime, scaling) from a snapshot.
func contractFromDetails(d *dashboard.ServiceDetails) *contract.Contract {
	c := &contract.Contract{
		Service: contract.ServiceIdentity{Name: d.Name, Version: d.Version},
	}
	for _, i := range d.Interfaces {
		c.Interfaces = append(c.Interfaces, contract.Interface{
			Name: i.Name, Type: i.Type, Port: i.Port, Visibility: i.Visibility,
		})
	}
	for _, dep := range d.Dependencies {
		c.Dependencies = append(c.Dependencies, contract.Dependency{
			Name: dep.Name, Ref: dep.Ref, Required: dep.Required, Compatibility: dep.Compatibility,
		})
	}
	if r := d.Runtime; r != nil {
		c.Runtime = &contract.Runtime{
			Workload: r.Workload,
			State: contract.State{
				Type:            r.StateType,
				DataCriticality: r.DataCriticality,
				Persistence:     contract.Persistence{Scope: r.PersistenceScope, Durability: r.PersistenceDurability},
			},
		}
		if r.HealthInterface != "" {
			c.Runtime.Health = &contract.Health{Interface: r.HealthInterface, Path: r.HealthPath}
		}
		if r.MetricsInterface != "" {
			c.Runtime.Metrics = &contract.Metrics{Interface: r.MetricsInterface, Path: r.MetricsPath}
		}
	}
	if s := d.Scaling; s != nil {
		c.Scaling = &contract.Scaling{Replicas: s.Replicas}
		if s.Min != nil {
			c.Scaling.Min = *s.Min
		}
		if s.Max != nil {
			c.Scaling.Max = *s.Max
		}
	}
	return c
}

func collectAllContracts(c *contract.Contract, gr *graph.Result) []*contract.Contract {
	if gr == nil || gr.Root == nil {
		return []*contract.Contract{c}
	}
	// BFS by depth so Mermaid renders services in natural layers (root → leaves).
	var all []*contract.Contract
	seen := map[string]bool{}
	queue := []*graph.Node{gr.Root}
	seen[gr.Root.Name] = true
	for len(queue) > 0 {
		node := queue[0]
		queue = queue[1:]
		if node.Contract != nil {
			all = append(all, node.Contract)
		}
		for _, edge := range node.Dependencies {
			if edge.Node == nil || edge.Shared || seen[edge.Node.Name] {
				continue
			}
			seen[edge.Node.Name] = true
			queue = append(queue, edge.Node)
		}
	}
	return all
}

func anyPublicInterface(contracts []*contract.Contract) bool {
	for _, sc := range contracts {
		for _, iface := range sc.Interfaces {
			if iface.Visibility == contract.VisibilityPublic {
				return true
			}
		}
	}
	return false
}

func writeDependencyEdges(b *strings.Builder, c *contract.Contract, gr *graph.Result) {
	if gr != nil && gr.Root != nil && len(gr.Root.Dependencies) > 0 {
		fmt.Fprintln(b)
		writeMermaidEdges(b, gr.Root)
		return
	}
	if len(c.Dependencies) == 0 {
		return
	}
	fmt.Fprintln(b)
	svcID := sanitizeMermaidID(c.Service.Name)
	for _, dep := range c.Dependencies {
		name := depName(dep.Ref)
		depID := "dep_" + sanitizeMermaidID(name)
		if dep.Required {
			fmt.Fprintf(b, "  %s -->|\"required · %s\"| %s[\"%s\"]\n", svcID, dep.Compatibility, depID, name)
		} else {
			fmt.Fprintf(b, "  %s -.->|\"optional · %s\"| %s[\"%s\"]\n", svcID, dep.Compatibility, depID, name)
		}
	}
}

func buildStateLabel(c *contract.Contract) string {
	label := fmt.Sprintf("%s · %s criticality", c.Runtime.State.Type, c.Runtime.State.DataCriticality)
	if c.Runtime.State.Persistence.Scope != "" {
		label += fmt.Sprintf(" · %s %s", c.Runtime.State.Persistence.Scope, c.Runtime.State.Persistence.Durability)
	}
	if c.Scaling != nil {
		if c.Scaling.Replicas != nil {
			label += fmt.Sprintf(" · %d replicas", *c.Scaling.Replicas)
		} else {
			label += fmt.Sprintf(" · %d–%d replicas", c.Scaling.Min, c.Scaling.Max)
		}
	}
	return label
}

func buildIfaceLabel(iface contract.Interface, c *contract.Contract) string {
	label := iface.Name + "<br/>" + iface.Type
	if iface.Port != nil {
		label += fmt.Sprintf(" :%d", *iface.Port)
	}
	if iface.Visibility != "" {
		label += "<br/>" + iface.Visibility
	}
	if c.Runtime != nil && c.Runtime.Health != nil && iface.Name == c.Runtime.Health.Interface {
		label += "<br/>♥ health"
	}
	if c.Runtime != nil && c.Runtime.Metrics != nil && iface.Name == c.Runtime.Metrics.Interface {
		label += "<br/>📊 metrics"
	}
	return label
}

func writeServiceSubgraph(b *strings.Builder, c *contract.Contract, hasExternal bool) {
	svcID := sanitizeMermaidID(c.Service.Name)
	fmt.Fprintf(b, "  subgraph %s[\"%s v%s\"]\n", svcID, c.Service.Name, c.Service.Version)
	fmt.Fprintln(b, "    direction TB")
	hasInnerNodes := false
	if c.Runtime != nil {
		hasInnerNodes = true
		fmt.Fprintf(b, "    %s_state[(\"%s\")]\n", svcID, buildStateLabel(c))
	}
	if len(c.Interfaces) > 0 {
		hasInnerNodes = true
	}
	for _, iface := range c.Interfaces {
		nodeID := svcID + "_iface_" + sanitizeMermaidID(iface.Name)
		fmt.Fprintf(b, "    %s[\"%s\"]\n", nodeID, buildIfaceLabel(iface, c))
	}
	if !hasInnerNodes {
		fmt.Fprintf(b, "    %s_info[\"%s\"]\n", svcID, c.Service.Name)
	}
	fmt.Fprintln(b, "  end")
	fmt.Fprintln(b)
	for _, iface := range c.Interfaces {
		if hasExternal && iface.Visibility == contract.VisibilityPublic {
			nodeID := svcID + "_iface_" + sanitizeMermaidID(iface.Name)
			fmt.Fprintf(b, "  external --> %s\n", nodeID)
		}
	}
}

func writeMermaidEdges(b *strings.Builder, node *graph.Node) {
	seen := map[string]bool{}
	walkMermaidEdges(b, node, seen)
}

func walkMermaidEdges(b *strings.Builder, node *graph.Node, seen map[string]bool) {
	if node == nil {
		return
	}
	for _, edge := range node.Dependencies {
		if edge.Node == nil {
			continue
		}
		fromID := sanitizeMermaidID(node.Name)
		toID := sanitizeMermaidID(edge.Node.Name)
		key := fromID + "-->" + toID
		if seen[key] {
			continue
		}
		seen[key] = true
		fmt.Fprintf(b, "  %s --> %s\n", fromID, toID)
		if !edge.Shared {
			walkMermaidEdges(b, edge.Node, seen)
		}
	}
}

var nonAlphanumeric = regexp.MustCompile(`[^a-zA-Z0-9]`)

func sanitizeMermaidID(s string) string {
	return nonAlphanumeric.ReplaceAllString(s, "")
}

func depName(ref string) string {
	// Strip tag or digest suffix
	name := ref
	if i := strings.LastIndex(name, "@"); i != -1 {
		name = name[:i]
	}
	if i := strings.LastIndex(name, ":"); i != -1 {
		name = name[:i]
	}
	// Extract last path component
	if i := strings.LastIndex(name, "/"); i != -1 {
		name = name[i+1:]
	}
	return name
}

// ── §3 Interfaces ──────────────────────────────────────────────────────

func writeInterfaces(b *strings.Builder, d *dashboard.ServiceDetails, num *sectionNumberer) {
	if len(d.Interfaces) == 0 {
		return
	}
	fmt.Fprintf(b, "## %s. Interfaces\n\n", num.Next(1))
	writeInterfaceTable(b, d.Interfaces)
	for _, i := range d.Interfaces {
		if len(i.Endpoints) == 0 {
			continue
		}
		fmt.Fprintf(b, "### %s. %s\n\n", num.Next(2), interfaceHeadingByType(i.Type, i.Name))
		fmt.Fprintln(b, "| Method | Path | Summary |")
		fmt.Fprintln(b, "|--------|------|---------|")
		for _, ep := range i.Endpoints {
			fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", strings.ToUpper(ep.Method), ep.Path, dashText(ep.Summary))
		}
		fmt.Fprintln(b)
	}
}

func writeInterfaceTable(b *strings.Builder, ifaces []dashboard.InterfaceInfo) {
	fmt.Fprintln(b, "| Name | Type | Port | Visibility |")
	fmt.Fprintln(b, "|------|------|------|------------|")
	for _, i := range ifaces {
		port := "—"
		if i.Port != nil {
			port = fmt.Sprintf("`%d`", *i.Port)
		}
		vis := "—"
		if i.Visibility != "" {
			vis = fmt.Sprintf("`%s`", i.Visibility)
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n", i.Name, i.Type, port, vis)
	}
	fmt.Fprintln(b)
}

func interfaceHeadingByType(t, name string) string {
	switch t {
	case contract.InterfaceTypeHTTP:
		return fmt.Sprintf("HTTP Interface: %s", name)
	case contract.InterfaceTypeGRPC:
		return fmt.Sprintf("gRPC Interface: %s", name)
	case contract.InterfaceTypeEvent:
		return fmt.Sprintf("Event Interface: %s", name)
	default:
		return fmt.Sprintf("%s Interface: %s", capitalizeFirst(t), name)
	}
}

// ── §4 Configuration ───────────────────────────────────────────────────

func writeConfiguration(b *strings.Builder, d *dashboard.ServiceDetails, num *sectionNumberer) {
	if len(d.Configurations) == 0 {
		return
	}
	fmt.Fprintf(b, "## %s. Configuration\n\n", num.Next(1))
	writeConfigList(b, d.Configurations)
}

// writeConfigList renders each configuration scope: a remote reference, a
// resolved values table, or a "no properties" note. Multi-scope configs are
// labelled by name. Shared by the root section and the per-dependency detail.
func writeConfigList(b *strings.Builder, configs []dashboard.ConfigurationInfo) {
	multi := len(configs) > 1
	for _, cfg := range configs {
		if multi {
			name := cfg.Name
			if name == "" {
				name = "default"
			}
			fmt.Fprintf(b, "_%s_\n\n", name)
		}
		if cfg.Ref != "" {
			fmt.Fprintf(b, "References: `%s`\n\n", escapeMarkdownCell(cfg.Ref))
			continue
		}
		if len(cfg.Values) == 0 {
			fmt.Fprintln(b, "_No configurable properties._")
			fmt.Fprintln(b)
			continue
		}
		fmt.Fprintln(b, "| Property | Type | Value |")
		fmt.Fprintln(b, "|----------|------|-------|")
		for _, p := range cfg.Values {
			fmt.Fprintf(b, "| `%s` | `%s` | `%s` |\n", escapeMarkdownCell(p.Key), escapeMarkdownCell(p.Type), escapeMarkdownCell(p.Value))
		}
		fmt.Fprintln(b)
	}
}

// ── §5 Policies ────────────────────────────────────────────────────────

func writePolicies(b *strings.Builder, d *dashboard.ServiceDetails, num *sectionNumberer) {
	if len(d.Policies) == 0 {
		return
	}
	fmt.Fprintf(b, "## %s. Policies\n\n", num.Next(1))
	fmt.Fprintln(b, "| Name | Type | Source |")
	fmt.Fprintln(b, "|------|------|--------|")
	for _, p := range d.Policies {
		if p.Ref != "" {
			fmt.Fprintf(b, "| `%s` | Remote | `%s` |\n", p.Name, escapeMarkdownCell(p.Ref))
		} else {
			fmt.Fprintf(b, "| `%s` | Local | `%s` |\n", p.Name, escapeMarkdownCell(p.Schema))
		}
	}
	fmt.Fprintln(b)
}

// ── §6 Dependencies ────────────────────────────────────────────────────

func writeDependencies(b *strings.Builder, d *dashboard.ServiceDetails, gr *graph.Result, num *sectionNumberer) {
	if len(d.Dependencies) == 0 {
		return
	}
	fmt.Fprintf(b, "## %s. Dependencies\n\n", num.Next(1))
	writeDependencyTable(b, d.Dependencies)
	for _, node := range collectFlatDependencyNodes(gr) {
		writeDependencyDetail(b, node)
	}
}

func writeDependencyTable(b *strings.Builder, deps []dashboard.DependencyInfo) {
	fmt.Fprintln(b, "| Name | Reference | Compatibility | Required | Locked version | Locked digest | Drift |")
	fmt.Fprintln(b, "|------|-----------|---------------|----------|----------------|---------------|-------|")
	for _, dep := range deps {
		req := "No"
		if dep.Required {
			req = "Yes"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s | %s | %s | %s |\n",
			escapeMarkdownCell(dep.Name), escapeMarkdownCell(dep.Ref), dash(dep.Compatibility),
			req, dash(dep.LockedVersion), dash(dep.LockedDigest), dash(dep.DriftStatus))
	}
	fmt.Fprintln(b)
}

// collectFlatDependencyNodes returns all unique resolved dependency nodes
// in DFS-discovery order, flattened (no nesting).
func collectFlatDependencyNodes(gr *graph.Result) []*graph.Node {
	if gr == nil || gr.Root == nil {
		return nil
	}
	var nodes []*graph.Node
	seen := map[string]bool{}
	var walk func(edges []graph.Edge)
	walk = func(edges []graph.Edge) {
		for _, edge := range edges {
			if edge.Node == nil || edge.Node.Contract == nil || seen[edge.Node.Name] {
				continue
			}
			seen[edge.Node.Name] = true
			nodes = append(nodes, edge.Node)
			walk(edge.Node.Dependencies)
		}
	}
	walk(gr.Root.Dependencies)
	return nodes
}

// writeDependencyDetail renders a collapsible per-dependency snapshot built from
// the resolved graph node via the same ServiceDetails mapping the dashboard
// uses, so the detail matches the dashboard's view of that dependency.
func writeDependencyDetail(b *strings.Builder, node *graph.Node) {
	nd := dashboard.ServiceDetailsFromBundle(&contract.Bundle{Contract: node.Contract, FS: node.FS}, "local")
	fmt.Fprintf(b, "<details>\n<summary><strong>%s</strong> <code>v%s</code></summary>\n\n", nd.Name, nd.Version)
	if nd.Runtime != nil {
		fmt.Fprintln(b, "**Runtime**")
		fmt.Fprintln(b)
		writeRuntimeTable(b, nd)
	}
	if len(nd.Interfaces) > 0 {
		fmt.Fprintln(b, "**Interfaces**")
		fmt.Fprintln(b)
		writeInterfaceTable(b, nd.Interfaces)
	}
	if len(nd.Configurations) > 0 {
		fmt.Fprintln(b, "**Configuration**")
		fmt.Fprintln(b)
		writeConfigList(b, nd.Configurations)
	}
	if len(nd.Dependencies) > 0 {
		fmt.Fprintln(b, "**Dependencies**")
		fmt.Fprintln(b)
		writeDependencyTable(b, nd.Dependencies)
	}
	fmt.Fprintln(b, "</details>")
	fmt.Fprintln(b)
}

// ── §7 Readiness ───────────────────────────────────────────────────────

func writeReadiness(b *strings.Builder, d *dashboard.ServiceDetails, num *sectionNumberer) {
	if d.Readiness == nil {
		return
	}
	r := d.Readiness
	fmt.Fprintf(b, "## %s. Readiness\n\n", num.Next(1))
	fmt.Fprintf(b, "Score `%d/100` · gate `%d`", r.Score, r.MinScore)
	if r.Expires != "" {
		fmt.Fprintf(b, " · expires `%s`", escapeMarkdownCell(r.Expires))
	}
	fmt.Fprintln(b)
	fmt.Fprintln(b)

	if len(r.Checks) > 0 {
		fmt.Fprintln(b, "| ID | Type | Category | Status | Evidence | Weight | Description |")
		fmt.Fprintln(b, "|----|------|----------|--------|----------|-------:|-------------|")
		for _, ch := range r.Checks {
			fmt.Fprintf(b, "| `%s` | `%s` | %s | `%s` | %s | %d | %s |\n",
				escapeMarkdownCell(ch.ID), escapeMarkdownCell(ch.Type), dash(ch.Category),
				escapeMarkdownCell(ch.Status), dash(ch.Evidence), ch.Weight, dashText(ch.Description))
		}
		fmt.Fprintln(b)
	}

	if len(r.Revisions) > 0 {
		fmt.Fprintln(b, "**Revision History**")
		fmt.Fprintln(b)
		fmt.Fprintln(b, "| Date | Version | Author | Description |")
		fmt.Fprintln(b, "|------|---------|--------|-------------|")
		for _, rev := range r.Revisions {
			fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n",
				escapeMarkdownCell(rev.Date), escapeMarkdownCell(rev.Version),
				escapeMarkdownCell(rev.Author), dashText(rev.Description))
		}
		fmt.Fprintln(b)
	}
}

// ── §8 SBOM ────────────────────────────────────────────────────────────

func writeSBOM(b *strings.Builder, d *dashboard.ServiceDetails, num *sectionNumberer) {
	if !hasSBOM(d) {
		return
	}
	fmt.Fprintf(b, "## %s. SBOM\n\n", num.Next(1))
	fmt.Fprintf(b, "Format `%s` · %d packages\n\n", d.SBOM.Format, len(d.SBOM.Packages))
	fmt.Fprintln(b, "| Package | Version | License | Supplier |")
	fmt.Fprintln(b, "|---------|---------|---------|----------|")
	for _, p := range d.SBOM.Packages {
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n", escapeMarkdownCell(p.Name), escapeMarkdownCell(p.Version), dash(p.License), dash(p.Supplier))
	}
	fmt.Fprintln(b)
}

// ── §9 Lockfile ────────────────────────────────────────────────────────

func writeLockfile(b *strings.Builder, d *dashboard.ServiceDetails, num *sectionNumberer) {
	if !hasLock(d) {
		return
	}
	fmt.Fprintf(b, "## %s. Lockfile\n\n", num.Next(1))
	if d.Lock.RootDigest != "" {
		fmt.Fprintf(b, "Root digest: `%s`\n\n", escapeMarkdownCell(d.Lock.RootDigest))
	}
	if len(d.Lock.Dependencies) > 0 {
		fmt.Fprintln(b, "| Dependency | Version | Digest |")
		fmt.Fprintln(b, "|------------|---------|--------|")
		for _, l := range d.Lock.Dependencies {
			fmt.Fprintf(b, "| `%s` | `%s` | `%s` |\n", escapeMarkdownCell(l.Name), escapeMarkdownCell(l.Version), escapeMarkdownCell(l.Digest))
		}
		fmt.Fprintln(b)
	}
	if len(d.Lock.References) > 0 {
		fmt.Fprintln(b, "| Reference | Kind | Version | Digest |")
		fmt.Fprintln(b, "|-----------|------|---------|--------|")
		for _, l := range d.Lock.References {
			fmt.Fprintf(b, "| `%s` | `%s` | `%s` | `%s` |\n", escapeMarkdownCell(l.Name), escapeMarkdownCell(l.Kind), escapeMarkdownCell(l.Version), escapeMarkdownCell(l.Digest))
		}
		fmt.Fprintln(b)
	}
}

// ── §10 Documentation ──────────────────────────────────────────────────

func writeBundleDocs(b *strings.Builder, d *dashboard.ServiceDetails, num *sectionNumberer) {
	if len(d.Docs) == 0 {
		return
	}
	fmt.Fprintf(b, "## %s. Documentation\n\n", num.Next(1))
	for _, dc := range d.Docs {
		fmt.Fprintf(b, "### %s. %s\n\n", num.Next(2), dc.Title)
		fmt.Fprintf(b, "_Source: `%s`_\n\n", dc.Path)
		fmt.Fprintln(b, dc.Content)
		if dc.Truncated {
			fmt.Fprintln(b, "\n_(truncated)_")
		}
		fmt.Fprintln(b)
	}
}

// ── metadata footer ────────────────────────────────────────────────────

func writeMetadataFooter(b *strings.Builder, d *dashboard.ServiceDetails) {
	if len(d.Metadata) == 0 {
		return
	}
	keys := make([]string, 0, len(d.Metadata))
	for k := range d.Metadata {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(b, "`%s: %s` ", k, d.Metadata[k])
	}
	fmt.Fprintln(b)
	fmt.Fprintln(b)
}

// ── shared cell helpers ────────────────────────────────────────────────

// escapeMarkdownCell escapes characters that would corrupt a Markdown table
// cell that wraps user-controlled text in a code span. GitHub-flavored Markdown
// resolves these backslash escapes inside table cells before code-span parsing,
// so a backtick no longer terminates the span early and a pipe no longer splits
// the cell into extra columns.
func escapeMarkdownCell(s string) string {
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "|", "\\|")
	return s
}

// dash renders a value as a code span, or an em-dash when empty.
func dash(s string) string {
	if s == "" {
		return "—"
	}
	return "`" + escapeMarkdownCell(s) + "`"
}

// dashText renders free-form text (no code span), or an em-dash when empty.
func dashText(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
