package doc

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/trianalab/pacto/pkg/contract"
	"github.com/trianalab/pacto/pkg/graph"
	"github.com/trianalab/pacto/pkg/validation"
)

// sectionNumberer tracks hierarchical section numbers (1, 1.1, 1.1.1, etc.).
type sectionNumberer struct {
	counters []int
}

// Next increments the counter at the given depth (1-based) and returns the
// full section number string. Deeper levels are reset when a shallower level
// is incremented.
func (n *sectionNumberer) Next(depth int) string {
	for len(n.counters) < depth {
		n.counters = append(n.counters, 0)
	}
	n.counters = n.counters[:depth]
	n.counters[depth-1]++
	parts := make([]string, depth)
	for i, v := range n.counters {
		parts[i] = strconv.Itoa(v)
	}
	return strings.Join(parts, ".")
}

// schemaDescriptions maps "path.enumValue" to its x-enum-descriptions text.
// Populated at init from the embedded JSON Schema.
var schemaDescriptions map[string]string

func init() {
	schemaDescriptions = loadSchemaDescriptions(validation.SchemaBytes())
}

func loadSchemaDescriptions(data []byte) map[string]string {
	dst := make(map[string]string)
	var root map[string]interface{}
	if err := json.Unmarshal(data, &root); err != nil {
		return dst
	}
	props, _ := root["properties"].(map[string]interface{})
	extractEnumDescriptions(props, "", dst)
	return dst
}

// extractEnumDescriptions recursively walks schema properties and collects
// x-enum-descriptions into the dst map keyed as "path.value".
func extractEnumDescriptions(props map[string]interface{}, prefix string, dst map[string]string) {
	for key, val := range props {
		obj, ok := val.(map[string]interface{})
		if !ok {
			continue
		}
		path := key
		if prefix != "" {
			path = prefix + "." + key
		}

		// Collect description for this field
		if desc, ok := obj["description"].(string); ok {
			dst[path] = desc
		}

		// Collect x-enum-descriptions
		if xDescs, ok := obj["x-enum-descriptions"].(map[string]interface{}); ok {
			for enumVal, enumDesc := range xDescs {
				if s, ok := enumDesc.(string); ok {
					dst[path+"."+enumVal] = s
				}
			}
		}

		// Recurse into nested properties
		if nested, ok := obj["properties"].(map[string]interface{}); ok {
			extractEnumDescriptions(nested, path, dst)
		}
	}
}

// Generate produces a Markdown document from a contract and its bundle filesystem.
// If gr is non-nil, the Mermaid diagram will show the full transitive dependency graph.
func Generate(c *contract.Contract, fsys fs.FS, gr *graph.Result) (string, error) {
	var b strings.Builder
	num := &sectionNumberer{}

	fmt.Fprintf(&b, "# %s\n\n", c.Service.Name)
	writeDescription(&b, c)
	writeTableOfContents(&b, c, gr)
	writeMermaidDiagram(&b, c, gr, num)
	writeInterfaces(&b, c, fsys, num)
	writeConfiguration(&b, c, fsys, num)
	writeDependencies(&b, c, gr, num)

	fmt.Fprintln(&b, "---")
	fmt.Fprintln(&b)
	writeMetadataFooter(&b, c)
	fmt.Fprintln(&b, "Generated by [Pacto](https://trianalab.github.io/pacto)")
	fmt.Fprintln(&b)

	return b.String(), nil
}

// schemaDesc looks up a description from the embedded schema.
// path is a dot-separated key like "runtime.state.type.stateful".
func schemaDesc(path string) string {
	return schemaDescriptions[path]
}

type conceptRow struct{ concept, value, desc string }

func writeDescription(b *strings.Builder, c *contract.Contract) {
	sentence := buildSummaryParagraph(c)
	fmt.Fprintln(b, sentence)
	fmt.Fprintln(b)

	rows := buildConceptRows(c)
	if len(rows) > 0 {
		fmt.Fprintln(b, "| Concept | Value | Description |")
		fmt.Fprintln(b, "|---------|-------|-------------|")
		for _, r := range rows {
			fmt.Fprintf(b, "| **%s** | `%s` | %s |\n", r.concept, r.value, r.desc)
		}
		fmt.Fprintln(b)
	}

	fmt.Fprintln(b, "For more information on contract concepts, see the [Contract Reference](https://trianalab.github.io/pacto/contract-reference/).")
	fmt.Fprintln(b)
}

func buildSummaryParagraph(c *contract.Contract) string {
	var head string
	if c.Runtime != nil {
		head = fmt.Sprintf("**%s** `v%s` is a `%s` `%s` workload", c.Service.Name, c.Service.Version, c.Runtime.State.Type, c.Runtime.Workload)
	} else {
		head = fmt.Sprintf("**%s** `v%s`", c.Service.Name, c.Service.Version)
	}
	parts := []string{head}
	if len(c.Interfaces) > 0 {
		noun := "interface"
		if len(c.Interfaces) > 1 {
			noun = "interfaces"
		}
		parts = append(parts, fmt.Sprintf("exposing %d %s", len(c.Interfaces), noun))
	}
	if len(c.Dependencies) > 0 {
		noun := "dependency"
		if len(c.Dependencies) > 1 {
			noun = "dependencies"
		}
		parts = append(parts, fmt.Sprintf("with %d %s", len(c.Dependencies), noun))
	}
	sentence := strings.Join(parts, " ") + "."

	if details := buildSummaryDetails(c); len(details) > 0 {
		sentence += " " + capitalizeFirst(strings.Join(details, ", ")) + "."
	}
	return sentence
}

func buildSummaryDetails(c *contract.Contract) []string {
	var details []string
	if c.Service.Owner != "" {
		details = append(details, fmt.Sprintf("owned by `%s`", c.Service.Owner))
	}
	if c.Service.Image != nil {
		visibility := "public"
		if c.Service.Image.Private {
			visibility = "private"
		}
		details = append(details, fmt.Sprintf("packaged as `%s` (`%s`)", c.Service.Image.Ref, visibility))
	}
	if c.Service.Chart != nil {
		details = append(details, fmt.Sprintf("deployed via Helm chart `%s` version `%s`", c.Service.Chart.Ref, c.Service.Chart.Version))
	}
	if c.Scaling != nil {
		if c.Scaling.Replicas != nil {
			details = append(details, fmt.Sprintf("runs `%d` replicas", *c.Scaling.Replicas))
		} else {
			details = append(details, fmt.Sprintf("scales from `%d` to `%d` replicas", c.Scaling.Min, c.Scaling.Max))
		}
	}
	return details
}

func buildConceptRows(c *contract.Contract) []conceptRow {
	if c.Runtime == nil {
		return nil
	}

	var rows []conceptRow

	// Workload and state type
	schemaRows := []struct {
		concept, path, value string
	}{
		{"Workload", "runtime.workload." + c.Runtime.Workload, c.Runtime.Workload},
		{"State", "runtime.state.type." + c.Runtime.State.Type, c.Runtime.State.Type},
	}
	for _, sr := range schemaRows {
		if desc := schemaDesc(sr.path); desc != "" {
			rows = append(rows, conceptRow{sr.concept, sr.value, capitalizeFirst(desc)})
		}
	}

	// Persistence rows (only when values are set)
	rows = appendPersistenceRows(rows, c)

	// Data criticality
	if desc := schemaDesc("runtime.state.dataCriticality." + c.Runtime.State.DataCriticality); desc != "" {
		rows = append(rows, conceptRow{"Data criticality", c.Runtime.State.DataCriticality, capitalizeFirst(desc)})
	}

	// Lifecycle rows
	rows = appendLifecycleRows(rows, c)

	return rows
}

func appendPersistenceRows(rows []conceptRow, c *contract.Contract) []conceptRow {
	if scope := c.Runtime.State.Persistence.Scope; scope != "" {
		if desc := schemaDesc("runtime.state.persistence.scope." + scope); desc != "" {
			rows = append(rows, conceptRow{"Persistence scope", scope, capitalizeFirst(desc)})
		}
	}
	if dur := c.Runtime.State.Persistence.Durability; dur != "" {
		if desc := schemaDesc("runtime.state.persistence.durability." + dur); desc != "" {
			rows = append(rows, conceptRow{"Persistence durability", dur, capitalizeFirst(desc)})
		}
	}
	return rows
}

func appendLifecycleRows(rows []conceptRow, c *contract.Contract) []conceptRow {
	if c.Runtime == nil || c.Runtime.Lifecycle == nil {
		return rows
	}
	if c.Runtime.Lifecycle.UpgradeStrategy != "" {
		if desc := schemaDesc("runtime.lifecycle.upgradeStrategy." + c.Runtime.Lifecycle.UpgradeStrategy); desc != "" {
			rows = append(rows, conceptRow{"Upgrade strategy", c.Runtime.Lifecycle.UpgradeStrategy, capitalizeFirst(desc)})
		}
	}
	if c.Runtime.Lifecycle.GracefulShutdownSeconds != nil {
		rows = append(rows, conceptRow{"Graceful shutdown", fmt.Sprintf("%ds", *c.Runtime.Lifecycle.GracefulShutdownSeconds), "Time allowed for in-flight requests to complete before termination"})
	}
	return rows
}

// headingAnchor generates a markdown-compatible anchor from a heading string.
// It lowercases, replaces spaces with hyphens, and strips colons and dots.
func headingAnchor(s string) string {
	a := strings.ToLower(s)
	a = strings.ReplaceAll(a, " ", "-")
	a = strings.ReplaceAll(a, ":", "")
	a = strings.ReplaceAll(a, ".", "")
	return a
}

func writeTableOfContents(b *strings.Builder, c *contract.Contract, gr *graph.Result) {
	num := &sectionNumberer{}
	fmt.Fprintln(b, "## Table of Contents")
	fmt.Fprintln(b)
	archSec := num.Next(1)
	fmt.Fprintf(b, "- [%s. Architecture](#%s)\n", archSec, headingAnchor(archSec+". Architecture"))
	if len(c.Interfaces) > 0 {
		sec := num.Next(1)
		fmt.Fprintf(b, "- [%s. Interfaces](#%s)\n", sec, headingAnchor(sec+". Interfaces"))
		for _, iface := range c.Interfaces {
			heading := interfaceHeading(iface)
			isec := num.Next(2)
			fmt.Fprintf(b, "  - [%s. %s](#%s)\n", isec, heading, headingAnchor(isec+". "+heading))
		}
	}
	if c.Configuration != nil && c.Configuration.Schema != "" {
		sec := num.Next(1)
		fmt.Fprintf(b, "- [%s. Configuration](#%s)\n", sec, headingAnchor(sec+". Configuration"))
	}
	if len(c.Dependencies) > 0 {
		sec := num.Next(1)
		fmt.Fprintf(b, "- [%s. Dependencies](#%s)\n", sec, headingAnchor(sec+". Dependencies"))
		for _, node := range collectFlatDependencyNodes(gr) {
			writeDependencyTOCEntry(b, node, num)
		}
	}
	fmt.Fprintln(b)
}

func writeDependencyTOCEntry(b *strings.Builder, node *graph.Node, num *sectionNumberer) {
	dc := node.Contract
	anchor := "dep-" + sanitizeMermaidID(dc.Service.Name)
	fmt.Fprintf(b, "  - [%s. %s](#%s)\n", num.Next(2), dc.Service.Name, anchor)
	if dc.Runtime != nil {
		fmt.Fprintf(b, "    - [%s. Runtime](#%s-runtime)\n", num.Next(3), anchor)
	}
	if len(dc.Interfaces) > 0 {
		fmt.Fprintf(b, "    - [%s. Interfaces](#%s-interfaces)\n", num.Next(3), anchor)
	}
	if dc.Configuration != nil && dc.Configuration.Schema != "" {
		fmt.Fprintf(b, "    - [%s. Configuration](#%s-configuration)\n", num.Next(3), anchor)
	}
	if len(dc.Dependencies) > 0 {
		fmt.Fprintf(b, "    - [%s. Dependencies](#%s-dependencies)\n", num.Next(3), anchor)
	}
}

var nonAlphanumeric = regexp.MustCompile(`[^a-zA-Z0-9]`)

func sanitizeMermaidID(s string) string {
	return nonAlphanumeric.ReplaceAllString(s, "")
}

func depName(ref string) string {
	// Strip tag or digest suffix
	name := ref
	if i := strings.LastIndex(name, "@"); i != -1 {
		name = name[:i]
	}
	if i := strings.LastIndex(name, ":"); i != -1 {
		name = name[:i]
	}
	// Extract last path component
	if i := strings.LastIndex(name, "/"); i != -1 {
		name = name[i+1:]
	}
	return name
}

func writeMermaidDiagram(b *strings.Builder, c *contract.Contract, gr *graph.Result, num *sectionNumberer) {
	fmt.Fprintf(b, "## %s. Architecture\n\n", num.Next(1))
	fmt.Fprintln(b, "```mermaid")
	fmt.Fprintln(b, "graph TB")

	allContracts := collectAllContracts(c, gr)

	hasPublic := anyPublicInterface(allContracts)
	if hasPublic {
		fmt.Fprintln(b, "  external([\"External User\"])")
		fmt.Fprintln(b)
	}

	for _, sc := range allContracts {
		writeServiceSubgraph(b, sc, hasPublic)
	}

	writeDependencyEdges(b, c, gr)

	fmt.Fprintln(b, "```")
	fmt.Fprintln(b)
}

func collectAllContracts(c *contract.Contract, gr *graph.Result) []*contract.Contract {
	if gr == nil || gr.Root == nil {
		return []*contract.Contract{c}
	}
	// BFS by depth so Mermaid renders services in natural layers (root → leaves).
	var all []*contract.Contract
	seen := map[string]bool{}
	queue := []*graph.Node{gr.Root}
	seen[gr.Root.Name] = true
	for len(queue) > 0 {
		node := queue[0]
		queue = queue[1:]
		if node.Contract != nil {
			all = append(all, node.Contract)
		}
		for _, edge := range node.Dependencies {
			if edge.Node == nil || edge.Shared || seen[edge.Node.Name] {
				continue
			}
			seen[edge.Node.Name] = true
			queue = append(queue, edge.Node)
		}
	}
	return all
}

func anyPublicInterface(contracts []*contract.Contract) bool {
	for _, sc := range contracts {
		for _, iface := range sc.Interfaces {
			if iface.Visibility == contract.VisibilityPublic {
				return true
			}
		}
	}
	return false
}

func writeDependencyEdges(b *strings.Builder, c *contract.Contract, gr *graph.Result) {
	if gr != nil && gr.Root != nil && len(gr.Root.Dependencies) > 0 {
		fmt.Fprintln(b)
		writeMermaidEdges(b, gr.Root)
		return
	}
	if len(c.Dependencies) == 0 {
		return
	}
	fmt.Fprintln(b)
	svcID := sanitizeMermaidID(c.Service.Name)
	for _, dep := range c.Dependencies {
		name := depName(dep.Ref)
		depID := "dep_" + sanitizeMermaidID(name)
		if dep.Required {
			fmt.Fprintf(b, "  %s -->|\"required · %s\"| %s[\"%s\"]\n", svcID, dep.Compatibility, depID, name)
		} else {
			fmt.Fprintf(b, "  %s -.->|\"optional · %s\"| %s[\"%s\"]\n", svcID, dep.Compatibility, depID, name)
		}
	}
}

func buildStateLabel(c *contract.Contract) string {
	label := fmt.Sprintf("%s · %s criticality", c.Runtime.State.Type, c.Runtime.State.DataCriticality)
	if c.Runtime.State.Persistence.Scope != "" {
		label += fmt.Sprintf(" · %s %s", c.Runtime.State.Persistence.Scope, c.Runtime.State.Persistence.Durability)
	}
	if c.Scaling != nil {
		if c.Scaling.Replicas != nil {
			label += fmt.Sprintf(" · %d replicas", *c.Scaling.Replicas)
		} else {
			label += fmt.Sprintf(" · %d–%d replicas", c.Scaling.Min, c.Scaling.Max)
		}
	}
	return label
}

func buildIfaceLabel(iface contract.Interface, c *contract.Contract) string {
	label := iface.Name + "<br/>" + iface.Type
	if iface.Port != nil {
		label += fmt.Sprintf(" :%d", *iface.Port)
	}
	if iface.Visibility != "" {
		label += "<br/>" + iface.Visibility
	}
	if c.Runtime != nil && c.Runtime.Health != nil && iface.Name == c.Runtime.Health.Interface {
		label += "<br/>♥ health"
	}
	if c.Runtime != nil && c.Runtime.Metrics != nil && iface.Name == c.Runtime.Metrics.Interface {
		label += "<br/>📊 metrics"
	}
	return label
}

func writeServiceSubgraph(b *strings.Builder, c *contract.Contract, hasExternal bool) {
	svcID := sanitizeMermaidID(c.Service.Name)
	fmt.Fprintf(b, "  subgraph %s[\"%s v%s\"]\n", svcID, c.Service.Name, c.Service.Version)
	fmt.Fprintln(b, "    direction TB")
	hasInnerNodes := false
	if c.Runtime != nil {
		hasInnerNodes = true
		fmt.Fprintf(b, "    %s_state[(\"%s\")]\n", svcID, buildStateLabel(c))
	}
	if len(c.Interfaces) > 0 {
		hasInnerNodes = true
	}
	for _, iface := range c.Interfaces {
		nodeID := svcID + "_iface_" + sanitizeMermaidID(iface.Name)
		fmt.Fprintf(b, "    %s[\"%s\"]\n", nodeID, buildIfaceLabel(iface, c))
	}
	if !hasInnerNodes {
		fmt.Fprintf(b, "    %s_info[\"%s\"]\n", svcID, c.Service.Name)
	}
	fmt.Fprintln(b, "  end")
	fmt.Fprintln(b)
	for _, iface := range c.Interfaces {
		if hasExternal && iface.Visibility == contract.VisibilityPublic {
			nodeID := svcID + "_iface_" + sanitizeMermaidID(iface.Name)
			fmt.Fprintf(b, "  external --> %s\n", nodeID)
		}
	}
}

func writeMermaidEdges(b *strings.Builder, node *graph.Node) {
	seen := map[string]bool{}
	walkMermaidEdges(b, node, seen)
}

func walkMermaidEdges(b *strings.Builder, node *graph.Node, seen map[string]bool) {
	if node == nil {
		return
	}
	for _, edge := range node.Dependencies {
		if edge.Node == nil {
			continue
		}
		fromID := sanitizeMermaidID(node.Name)
		toID := sanitizeMermaidID(edge.Node.Name)
		key := fromID + "-->" + toID
		if seen[key] {
			continue
		}
		seen[key] = true
		fmt.Fprintf(b, "  %s --> %s\n", fromID, toID)
		if !edge.Shared {
			walkMermaidEdges(b, edge.Node, seen)
		}
	}
}

func writeInterfacesTable(b *strings.Builder, interfaces []contract.Interface) {
	fmt.Fprintln(b, "| Name | Type | Port | Visibility |")
	fmt.Fprintln(b, "|------|------|------|------------|")
	for _, iface := range interfaces {
		port := "\u2014"
		if iface.Port != nil {
			port = fmt.Sprintf("`%d`", *iface.Port)
		}
		vis := "\u2014"
		if iface.Visibility != "" {
			vis = fmt.Sprintf("`%s`", iface.Visibility)
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n", iface.Name, iface.Type, port, vis)
	}
	fmt.Fprintln(b)
}

func writeInterfaceDetails(b *strings.Builder, c *contract.Contract, fsys fs.FS, level int, num *sectionNumberer) {
	var health *contract.Health
	var metrics *contract.Metrics
	if c.Runtime != nil {
		health = c.Runtime.Health
		metrics = c.Runtime.Metrics
	}
	for _, iface := range c.Interfaces {
		if iface.Type == contract.InterfaceTypeHTTP {
			writeHTTPInterfaceDetailLevel(b, iface, health, metrics, fsys, level, num)
		} else {
			writeNonHTTPInterfaceDetailLevel(b, iface, health, metrics, level, num)
		}
	}
}

func writeConfigurationTable(b *strings.Builder, props []Property) {
	fmt.Fprintln(b, "| Property | Type | Description | Default | Required |")
	fmt.Fprintln(b, "|----------|------|-------------|---------|----------|")
	for _, p := range props {
		def := "\u2014"
		if p.Default != "" {
			def = fmt.Sprintf("`%s`", p.Default)
		}
		req := "No"
		if p.Required {
			req = "Yes"
		}
		desc := p.Description
		if desc == "" {
			desc = "\u2014"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s | %s |\n", p.Name, p.Type, desc, def, req)
	}
	fmt.Fprintln(b)
}

func writeInterfaces(b *strings.Builder, c *contract.Contract, fsys fs.FS, num *sectionNumberer) {
	if len(c.Interfaces) == 0 {
		return
	}

	fmt.Fprintf(b, "## %s. Interfaces\n\n", num.Next(1))
	writeInterfacesTable(b, c.Interfaces)
	writeInterfaceDetails(b, c, fsys, 3, num)
}

func writeConfiguration(b *strings.Builder, c *contract.Contract, fsys fs.FS, num *sectionNumberer) {
	if c.Configuration == nil || c.Configuration.Schema == "" {
		return
	}

	props, err := readSchemaProperties(fsys, c.Configuration.Schema)
	if err != nil {
		fmt.Fprintf(b, "## %s. Configuration\n\n", num.Next(1))
		fmt.Fprintf(b, "_Could not read configuration schema: %v_\n\n", err)
		return
	}

	if len(props) == 0 {
		return
	}

	fmt.Fprintf(b, "## %s. Configuration\n\n", num.Next(1))
	writeConfigurationTable(b, props)
}

func interfaceHeading(iface contract.Interface) string {
	switch iface.Type {
	case contract.InterfaceTypeHTTP:
		return fmt.Sprintf("HTTP Interface: %s", iface.Name)
	case contract.InterfaceTypeGRPC:
		return fmt.Sprintf("gRPC Interface: %s", iface.Name)
	case contract.InterfaceTypeEvent:
		return fmt.Sprintf("Event Interface: %s", iface.Name)
	default:
		return fmt.Sprintf("%s Interface: %s", capitalizeFirst(iface.Type), iface.Name)
	}
}

func healthSuffix(ifaceName string, health *contract.Health) string {
	if health == nil || health.Interface != ifaceName {
		return ""
	}
	var parts []string
	if health.Path != "" {
		parts = append(parts, fmt.Sprintf("owns the health path under `%s`", health.Path))
	}
	if health.InitialDelaySeconds != nil {
		parts = append(parts, fmt.Sprintf("requires an initial delay of `%ds`", *health.InitialDelaySeconds))
	}
	if len(parts) > 0 {
		return " It " + strings.Join(parts, " and ") + "."
	}
	return ""
}

func metricsSuffix(ifaceName string, metrics *contract.Metrics) string {
	if metrics == nil || metrics.Interface != ifaceName {
		return ""
	}
	if metrics.Path != "" {
		return fmt.Sprintf(" It serves metrics at `%s`.", metrics.Path)
	}
	return " It serves the metrics endpoint."
}

func writeInterfaceSentence(iface contract.Interface) string {
	s := fmt.Sprintf("The `%s` interface", iface.Name)
	if iface.Visibility != "" && iface.Port != nil {
		s += fmt.Sprintf(" is `%s` and exposes port `%d`", iface.Visibility, *iface.Port)
	} else if iface.Visibility != "" {
		s += fmt.Sprintf(" is `%s`", iface.Visibility)
	} else if iface.Port != nil {
		s += fmt.Sprintf(" exposes port `%d`", *iface.Port)
	}
	return s
}

func writeHTTPInterfaceDetailLevel(b *strings.Builder, iface contract.Interface, health *contract.Health, metrics *contract.Metrics, fsys fs.FS, level int, num *sectionNumberer) {
	writeHeading(b, level, interfaceHeading(iface), num)
	fmt.Fprintf(b, "%s.%s%s\n\n", writeInterfaceSentence(iface), healthSuffix(iface.Name, health), metricsSuffix(iface.Name, metrics))

	if iface.Contract == "" {
		return
	}

	endpoints, err := ReadOpenAPIEndpoints(fsys, iface.Contract)
	if err != nil {
		fmt.Fprintf(b, "_Could not read OpenAPI spec: %v_\n\n", err)
		return
	}

	if len(endpoints) == 0 {
		return
	}

	fmt.Fprintln(b, "| Method | Path | Summary |")
	fmt.Fprintln(b, "|--------|------|---------|")

	for _, ep := range endpoints {
		summary := ep.Summary
		if summary == "" {
			summary = "\u2014"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", strings.ToUpper(ep.Method), ep.Path, summary)
	}
	fmt.Fprintln(b)
}

func writeNonHTTPInterfaceDetailLevel(b *strings.Builder, iface contract.Interface, health *contract.Health, metrics *contract.Metrics, level int, num *sectionNumberer) {
	writeHeading(b, level, interfaceHeading(iface), num)

	desc := writeInterfaceSentence(iface)
	if iface.Contract != "" {
		desc += fmt.Sprintf(". Its contract is defined in `%s`", iface.Contract)
	}
	fmt.Fprintf(b, "%s.%s%s\n\n", desc, healthSuffix(iface.Name, health), metricsSuffix(iface.Name, metrics))
}

// writeHeading writes a heading at the given level. Levels 1-4 use markdown (#),
// levels 5+ use HTML tags. The numberer depth is hLevel-1 (h2 → depth 1, h3 → depth 2, etc.).
func writeHeading(b *strings.Builder, hLevel int, text string, num *sectionNumberer) {
	prefix := ""
	if num != nil {
		prefix = num.Next(hLevel-1) + ". "
	}
	if hLevel <= 4 {
		fmt.Fprintf(b, "%s %s%s\n\n", strings.Repeat("#", hLevel), prefix, text)
	} else {
		fmt.Fprintf(b, "<h%d>%s%s</h%d>\n\n", hLevel, prefix, text, hLevel)
	}
}

func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func writeDependencies(b *strings.Builder, c *contract.Contract, gr *graph.Result, num *sectionNumberer) {
	if len(c.Dependencies) == 0 {
		return
	}

	fmt.Fprintf(b, "## %s. Dependencies\n\n", num.Next(1))
	writeDependencyTable(b, c.Dependencies)

	if gr != nil && gr.Root != nil {
		nodes := collectFlatDependencyNodes(gr)
		for _, node := range nodes {
			writeDependencyDetail(b, node, num)
		}
	}
}

// collectFlatDependencyNodes returns all unique resolved dependency nodes
// in DFS-discovery order, flattened (no nesting).
func collectFlatDependencyNodes(gr *graph.Result) []*graph.Node {
	if gr == nil || gr.Root == nil {
		return nil
	}
	var nodes []*graph.Node
	seen := map[string]bool{}
	var walk func(edges []graph.Edge)
	walk = func(edges []graph.Edge) {
		for _, edge := range edges {
			if edge.Node == nil || edge.Node.Contract == nil || seen[edge.Node.Name] {
				continue
			}
			seen[edge.Node.Name] = true
			nodes = append(nodes, edge.Node)
			walk(edge.Node.Dependencies)
		}
	}
	walk(gr.Root.Dependencies)
	return nodes
}

func writeDependencyTable(b *strings.Builder, deps []contract.Dependency) {
	fmt.Fprintln(b, "| Reference | Compatibility | Required |")
	fmt.Fprintln(b, "|-----------|---------------|----------|")
	for _, dep := range deps {
		req := "No"
		if dep.Required {
			req = "Yes"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", dep.Ref, dep.Compatibility, req)
	}
	fmt.Fprintln(b)
}

func writeDependencyDetail(b *strings.Builder, node *graph.Node, num *sectionNumberer) {
	dc := node.Contract
	anchor := "dep-" + sanitizeMermaidID(dc.Service.Name)
	depSec := num.Next(2)
	fmt.Fprintf(b, "<details id=\"%s\">\n<summary><h3>%s. %s <code>v%s</code></h3></summary>\n\n", anchor, depSec, dc.Service.Name, dc.Service.Version)
	fmt.Fprintln(b, buildSummaryParagraph(dc))
	fmt.Fprintln(b)

	rows := buildConceptRows(dc)
	if len(rows) > 0 {
		fmt.Fprintf(b, "<h4 id=\"%s-runtime\">%s. Runtime</h4>\n\n", anchor, num.Next(3))
		fmt.Fprintln(b, "| Concept | Value | Description |")
		fmt.Fprintln(b, "|---------|-------|-------------|")
		for _, row := range rows {
			fmt.Fprintf(b, "| **%s** | `%s` | %s |\n", row.concept, row.value, row.desc)
		}
		fmt.Fprintln(b)
	}

	if len(dc.Interfaces) > 0 {
		fmt.Fprintf(b, "<h4 id=\"%s-interfaces\">%s. Interfaces</h4>\n\n", anchor, num.Next(3))
		writeInterfacesTable(b, dc.Interfaces)
		writeInterfaceDetails(b, dc, node.FS, 5, num)
	}

	if dc.Configuration != nil && dc.Configuration.Schema != "" && node.FS != nil {
		props, err := readSchemaProperties(node.FS, dc.Configuration.Schema)
		if err != nil {
			fmt.Fprintf(b, "<h4 id=\"%s-configuration\">%s. Configuration</h4>\n\n", anchor, num.Next(3))
			fmt.Fprintf(b, "_Could not read configuration schema: %v_\n\n", err)
		} else if len(props) > 0 {
			fmt.Fprintf(b, "<h4 id=\"%s-configuration\">%s. Configuration</h4>\n\n", anchor, num.Next(3))
			writeConfigurationTable(b, props)
		}
	}

	if len(dc.Dependencies) > 0 {
		fmt.Fprintf(b, "<h4 id=\"%s-dependencies\">%s. Dependencies</h4>\n\n", anchor, num.Next(3))
		writeDependencyTable(b, dc.Dependencies)
	}

	fmt.Fprintln(b, "</details>")
	fmt.Fprintln(b)
}

func writeMetadataFooter(b *strings.Builder, c *contract.Contract) {
	if len(c.Metadata) == 0 {
		return
	}

	keys := make([]string, 0, len(c.Metadata))
	for k := range c.Metadata {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		fmt.Fprintf(b, "`%s: %v` ", k, c.Metadata[k])
	}
	fmt.Fprintln(b)
	fmt.Fprintln(b)
}
