name: CI (PR)

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./.github/actions/ci
        with:
          target: ci-static
          golangci-lint: 'true'

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./.github/actions/ci
        with:
          target: ci-test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./.github/actions/ci
        with:
          target: e2e
